package com.ml.tblandroidtxt;

/** Stable append-only result vocabulary for the v17 authoritative identity stores. */
public enum EditorialIdentityPersistenceCode {
    APPENDED,
    ALREADY_EXISTS,
    DUPLICATE_IMMUTABLE_RECORD,
    INVALID_IMMUTABLE_RECORD,
    IDENTITY_UNATTESTED,
    PROJECT_REVISION_REQUIRED,
    INPUT_SCOPE_REQUIRED,
    INPUT_MANIFEST_INCOMPLETE,
    RUN_CONTEXT_REQUIRED,
    RUN_CONTEXT_NOT_CLOSED,
    TRUSTED_PROFILE_CONTEXT_MISMATCH,
    COMPATIBILITY_CONTEXT_MISMATCH,
    ATTEMPT_ALLOCATION_FAILURE,
    BINDING_MISMATCH,
    LINEAGE_PERSISTENCE_FAILURE,
    IMMUTABLE_RECORD_MUTATION,
    FOREIGN_KEY_RESTRICTED
}
