package com.ml.tblandroidtxt;

import org.json.JSONArray;
import org.json.JSONObject;
import java.util.List;

/** Transaction-like L1 job runner: it creates a resumable run record before one isolated model call. */
public final class EditorialL1Runner {
    public interface Client { OpenAICompatibleClient.ChatResult audit(AppSettings settings,PromptPair prompt,String requestId) throws Exception; }
    public static final class Result { public final long runId; public final String report; Result(long runId,String report){this.runId=runId;this.report=report;} }
    private final EditorialRepository repository; private final Client client;
    public EditorialL1Runner(EditorialRepository repository){this(repository,(s,p,id)->OpenAICompatibleClient.chatWithUsage(s,p,s.maxOutputTokens,id));}
    EditorialL1Runner(EditorialRepository repository,Client client){this.repository=repository;this.client=client;}
    public Result run(long chapterId,AppSettings settings) throws Exception {
        EditorialRepository.Chapter chapter=repository.getChapter(chapterId);if(chapter==null)throw new IllegalArgumentException("Editorial chapter not found");if(chapter.state!=EditorialWorkflowV5.ChapterState.L1_READY)throw new IllegalStateException("L1 is not ready for this chapter");
        List<EditorialRepository.AssetSnapshot> assets=repository.chapterAssets(chapterId);if(totalChars(assets)>EditorialL1ContextBuilder.MAX_INLINE_SOURCE_CHARS)return runSegmented(chapterId,settings,assets);
        EditorialL1ContextBuilder.Context context=EditorialL1ContextBuilder.build(chapterId,assets);String promptHash=HashUtil.sha256(context.prompt.system+"\n"+context.prompt.user);long runId=repository.createRun(chapterId,"L1",settings.provider,settings.model,promptHash,HashUtil.sha256(EditorialEvidenceSchema.VERSION),context.manifestJson);
        repository.saveEvidence(runId,"RAW_MAP",context.rawMapJson);repository.saveEvidence(runId,"L1_CONTEXT_MANIFEST",context.manifestJson);repository.updateRunState(runId,"RUNNING");repository.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L1_READY,EditorialWorkflowV5.ChapterState.L1_RUNNING);
        try { OpenAICompatibleClient.ChatResult response=client.audit(settings,context.prompt,"editorial-l1:"+runId);String error=EditorialEvidenceValidator.validateL1Report(response.content);if(error!=null)throw new IllegalArgumentException("L1 output contract failed: "+error);JSONObject root=new JSONObject(response.content);if(!String.valueOf(chapterId).equals(root.optString("chapterId")))throw new IllegalArgumentException("L1 output chapterId does not match run");
            persistScenesAndGates(runId,root);String report=render(root);repository.saveEvidence(runId,"REPORT_L1_JSON",response.content);repository.saveEvidence(runId,"REPORT_L1_TEXT",report);repository.saveEvidence(runId,"L1_USAGE",usage(response));repository.updateRunState(runId,"CLOSED");repository.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L1_RUNNING,EditorialWorkflowV5.ChapterState.L1_CLOSED);return new Result(runId,report);
        } catch(Exception error) { repository.updateRunState(runId,"FAILED");repository.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L1_RUNNING,EditorialWorkflowV5.ChapterState.FAILED);throw error; }
    }
    private Result runSegmented(long chapterId,AppSettings settings,List<EditorialRepository.AssetSnapshot> assets) throws Exception {
        EditorialSceneSegmenter.Plan rawPlan=EditorialL1ContextBuilder.segmentRawForL1(assets);List<EditorialDraftSceneMapper.Pair> pairs=EditorialL1ContextBuilder.mapDraftForL1(assets);String manifest=segmentedManifest(chapterId,assets,rawPlan,pairs);long runId=repository.createRun(chapterId,"L1",settings.provider,settings.model,HashUtil.sha256(EditorialL1SceneContract.schema()),HashUtil.sha256(EditorialEvidenceSchema.VERSION),manifest);
        repository.saveEvidence(runId,"RAW_MAP",rawPlan.ledgerJson());repository.saveEvidence(runId,"L1_CONTEXT_MANIFEST",manifest);repository.saveEvidence(runId,"L1_DRAFT_MAPPING",mappingJson(pairs));repository.updateRunState(runId,"RUNNING");repository.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L1_READY,EditorialWorkflowV5.ChapterState.L1_RUNNING);try{pairs=resolvePairs(settings,assets,rawPlan,pairs,runId);}catch(Exception error){failRun(chapterId,runId,"mapping",error);throw error;}
        return executeSegmented(chapterId,settings,assets,rawPlan,pairs,runId,false);
    }
    public Result retryFailedScene(long chapterId,AppSettings settings) throws Exception {
        EditorialRepository.Chapter chapter=repository.getChapter(chapterId);if(chapter==null||chapter.state!=EditorialWorkflowV5.ChapterState.FAILED)throw new IllegalStateException("No failed L1 checkpoint to retry");long runId=repository.latestRunId(chapterId,"L1");if(runId<=0)throw new IllegalStateException("Failed L1 run not found");List<EditorialRepository.AssetSnapshot> assets=repository.chapterAssets(chapterId);EditorialSceneSegmenter.Plan rawPlan=EditorialL1ContextBuilder.segmentRawForL1(assets);List<EditorialDraftSceneMapper.Pair> pairs=EditorialL1ContextBuilder.mapDraftForL1(assets);repository.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.FAILED,EditorialWorkflowV5.ChapterState.L1_READY);repository.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L1_READY,EditorialWorkflowV5.ChapterState.L1_RUNNING);repository.updateRunState(runId,"RUNNING");try{pairs=resolvePairs(settings,assets,rawPlan,pairs,runId);}catch(Exception error){failRun(chapterId,runId,"mapping",error);throw error;}return executeSegmented(chapterId,settings,assets,rawPlan,pairs,runId,true);
    }
    private Result executeSegmented(long chapterId,AppSettings settings,List<EditorialRepository.AssetSnapshot> assets,EditorialSceneSegmenter.Plan rawPlan,List<EditorialDraftSceneMapper.Pair> pairs,long runId,boolean reuseClosed) throws Exception {
        String activeScene="mapping";
        try {
            for(EditorialDraftSceneMapper.Pair pair:pairs)if(pair.status!=EditorialDraftSceneMapper.Status.ALIGNED)throw new IllegalStateException("Segmented L1 blocked: scene "+pair.ordinal+" mapping is "+pair.status);
            EditorialRepository.AssetSnapshot glossary=find(assets,EditorialWorkflowV5.AssetRole.GLOSSARY),pronoun=find(assets,EditorialWorkflowV5.AssetRole.PRONOUN);JSONArray scenes=new JSONArray(),issues=new JSONArray();int promptTokens=0,completionTokens=0,totalTokens=0;
            for(EditorialDraftSceneMapper.Pair pair:pairs){if(pair.raw.length()+pair.draft.length()+glossary.content.length()+pronoun.content.length()>EditorialL1ContextBuilder.MAX_INLINE_SOURCE_CHARS)throw new IllegalStateException("Segmented L1 scene "+pair.ordinal+" still exceeds safe context size");String sceneId=String.format(java.util.Locale.US,"scene-%03d",pair.ordinal);activeScene=sceneId;String payload=reuseClosed?repository.evidencePayload(runId,"L1_SCENE_"+sceneId):"";OpenAICompatibleClient.ChatResult response=null;if(EditorialL1SceneContract.validate(payload)!=null){PromptPair prompt=scenePrompt(chapterId,sceneId,pair,rawPlan.ledgerJson(),glossary.content,pronoun.content);response=client.audit(settings,prompt,"editorial-l1:"+runId+":"+sceneId);payload=response.content;}JSONObject scene=new JSONObject(payload);String validation=EditorialL1SceneContract.validate(payload);if(validation!=null)throw new IllegalArgumentException("L1 scene contract failed: "+validation);if(!sceneId.equals(scene.optString("sceneId"))||!pair.rawStart.equals(scene.optString("rawStart"))||!pair.rawEnd.equals(scene.optString("rawEnd")))throw new IllegalArgumentException("L1 scene anchors do not match checkpoint");repository.saveScene(runId,sceneId,pair.rawStart,pair.rawEnd,"CLOSED",scene.toString());if(response!=null){repository.saveEvidence(runId,"L1_SCENE_"+sceneId,payload);repository.saveEvidence(runId,"L1_SCENE_USAGE_"+sceneId,usage(response));promptTokens+=response.promptTokens;completionTokens+=response.completionTokens;totalTokens+=response.totalTokens;}scenes.put(new JSONObject().put("id",sceneId).put("rawStart",pair.rawStart).put("rawEnd",pair.rawEnd).put("coverage",scene.optString("coverage")).put("status","CLOSED"));JSONArray local=scene.getJSONArray("issues");for(int i=0;i<local.length();i++)issues.put(local.getJSONObject(i));}
            JSONObject gates=new JSONObject().put("coverage","CLOSED").put("fidelity","CLOSED").put("referenceVoice","CLOSED").put("continuityStructure","CLOSED");JSONObject reportJson=new JSONObject().put("schema",EditorialEvidenceSchema.VERSION).put("run","L1").put("chapterId",String.valueOf(chapterId)).put("scenes",scenes).put("issues",issues).put("gates",gates);String validation=EditorialEvidenceValidator.validateL1Report(reportJson.toString());if(validation!=null)throw new IllegalStateException("Aggregated L1 contract failed: "+validation);persistScenesAndGates(runId,reportJson);String report=render(reportJson);repository.saveEvidence(runId,"REPORT_L1_JSON",reportJson.toString());repository.saveEvidence(runId,"REPORT_L1_TEXT",report);repository.saveEvidence(runId,"L1_USAGE",new JSONObject().put("promptTokens",promptTokens).put("completionTokens",completionTokens).put("totalTokens",totalTokens).put("sceneCalls",pairs.size()).toString());repository.updateRunState(runId,"CLOSED");repository.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L1_RUNNING,EditorialWorkflowV5.ChapterState.L1_CLOSED);return new Result(runId,report);
        }catch(Exception error){failRun(chapterId,runId,activeScene,error);throw error;}
    }
    private static PromptPair scenePrompt(long chapterId,String sceneId,EditorialDraftSceneMapper.Pair pair,String chapterLedger,String glossary,String pronoun){String system="L1 diagnostic audit only. Never rewrite DRAFT. The complete RAW chapter ledger was created before DRAFT review. Return only JSON matching: "+EditorialL1SceneContract.schema();String user="CHAPTER: "+chapterId+"\nSCENE: "+sceneId+"\nEXPECTED RAW ANCHORS: "+pair.rawStart+" -> "+pair.rawEnd+"\nCHAPTER RAW LEDGER:\n"+chapterLedger+"\nGLOSSARY:\n"+glossary+"\nPRONOUN:\n"+pronoun+"\nRAW SCENE:\n"+pair.raw+"\nDRAFT SCENE:\n"+pair.draft+"\nAudit coverage, fidelity, reference/voice and continuity/structure. Close only after sequential comparison.";return new PromptPair(system,user);}
    private List<EditorialDraftSceneMapper.Pair> resolvePairs(AppSettings settings,List<EditorialRepository.AssetSnapshot> assets,EditorialSceneSegmenter.Plan rawPlan,List<EditorialDraftSceneMapper.Pair> pairs,long runId)throws Exception{boolean fallback=false;for(EditorialDraftSceneMapper.Pair p:pairs)if(p.status!=EditorialDraftSceneMapper.Status.ALIGNED){fallback=true;break;}if(!fallback)return pairs;EditorialModelSceneMapper.Result mapped=EditorialModelSceneMapper.map(settings,rawPlan,find(assets,EditorialWorkflowV5.AssetRole.DRAFT).content,(s,p,id)->client.audit(s,p,id),"editorial-l1-map:"+runId);repository.saveEvidence(runId,"L1_MODEL_MAPPING",mapped.evidence);return mapped.pairs;}
    private void failRun(long chapterId,long runId,String scene,Exception error)throws Exception{repository.saveEvidence(runId,"L1_FAILURE",new JSONObject().put("scene",scene).put("message",String.valueOf(error.getMessage())).toString());repository.updateRunState(runId,"FAILED");repository.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L1_RUNNING,EditorialWorkflowV5.ChapterState.FAILED);}
    private static String segmentedManifest(long chapterId,List<EditorialRepository.AssetSnapshot> assets,EditorialSceneSegmenter.Plan plan,List<EditorialDraftSceneMapper.Pair> pairs)throws Exception{JSONArray roles=new JSONArray();for(EditorialRepository.AssetSnapshot a:assets)roles.put(new JSONObject().put("role",a.role.name()).put("sha256",a.sha256));return new JSONObject().put("chapterId",String.valueOf(chapterId)).put("mode","SEGMENTED").put("rawHash",plan.map.sha256).put("mappingCount",pairs.size()).put("assets",roles).toString();}
    private static String mappingJson(List<EditorialDraftSceneMapper.Pair> pairs)throws Exception{JSONArray rows=new JSONArray();for(EditorialDraftSceneMapper.Pair p:pairs)rows.put(new JSONObject().put("scene",p.ordinal).put("rawStart",p.rawStart).put("rawEnd",p.rawEnd).put("status",p.status.name()));return rows.toString();}
    private static int totalChars(List<EditorialRepository.AssetSnapshot> assets){int n=0;for(EditorialRepository.AssetSnapshot a:assets)n+=a.content.length();return n;}private static EditorialRepository.AssetSnapshot find(List<EditorialRepository.AssetSnapshot> assets,EditorialWorkflowV5.AssetRole role){for(EditorialRepository.AssetSnapshot a:assets)if(a.role==role)return a;throw new IllegalArgumentException("Missing "+role);}
    private void persistScenesAndGates(long runId,JSONObject root) throws Exception {JSONArray scenes=root.getJSONArray("scenes");for(int i=0;i<scenes.length();i++){JSONObject scene=scenes.getJSONObject(i);repository.saveScene(runId,scene.getString("id"),scene.getString("rawStart"),scene.getString("rawEnd"),scene.getString("status"),scene.toString());}JSONObject gates=root.getJSONObject("gates");repository.saveGate(runId,EditorialWorkflowV5.Gate.COVERAGE,EditorialWorkflowV5.GateStatus.valueOf(gates.getString("coverage")),gates.toString());repository.saveGate(runId,EditorialWorkflowV5.Gate.FIDELITY,EditorialWorkflowV5.GateStatus.valueOf(gates.getString("fidelity")),gates.toString());repository.saveGate(runId,EditorialWorkflowV5.Gate.REFERENCE_VOICE,EditorialWorkflowV5.GateStatus.valueOf(gates.getString("referenceVoice")),gates.toString());repository.saveGate(runId,EditorialWorkflowV5.Gate.CONTINUITY_STRUCTURE,EditorialWorkflowV5.GateStatus.valueOf(gates.getString("continuityStructure")),gates.toString());}
    private static String render(JSONObject root) throws Exception {StringBuilder out=new StringBuilder("REPORT_L1\n\nA. Scope\nChapter: ").append(root.optString("chapterId")).append("\n\nB. Scene Ledger\n");JSONArray scenes=root.getJSONArray("scenes");for(int i=0;i<scenes.length();i++){JSONObject s=scenes.getJSONObject(i);out.append("- ").append(s.optString("id")).append(" | ").append(s.optString("rawStart")).append(" → ").append(s.optString("rawEnd")).append(" | ").append(s.optString("coverage")).append("\n");}out.append("\nC. Error Ledger\n");JSONArray issues=root.getJSONArray("issues");if(issues.length()==0)out.append("No reportable deviations.\n");for(int i=0;i<issues.length();i++){JSONObject x=issues.getJSONObject(i);out.append("- ").append(x.optString("id")).append(" [").append(x.optString("severity")).append(" / ").append(x.optString("category")).append("]\n  Raw: ").append(x.optString("rawAnchor")).append("\n  Draft: ").append(x.optString("draftAnchor")).append("\n  Current: ").append(x.optString("currentMeaning")).append("\n  Raw evidence: ").append(x.optString("rawEvidence")).append("\n  Impact: ").append(x.optString("deviationImpact")).append("\n  L2 scope: ").append(x.optString("l2Scope")).append("\n");}return out.toString();}
    private static String usage(OpenAICompatibleClient.ChatResult r) throws Exception {return new JSONObject().put("promptTokens",r.promptTokens).put("completionTokens",r.completionTokens).put("totalTokens",r.totalTokens).put("finishReason",r.finishReason).put("responseId",r.providerResponseId).toString();}
}
