package com.ml.tblandroidtxt;

import org.json.JSONObject;
import java.util.ArrayList;
import java.util.List;

/** Model-assisted mapping constrained to deterministic RAW/DRAFT anchors and monotonic full coverage. */
public final class EditorialModelSceneMapper {
    public interface Client { OpenAICompatibleClient.ChatResult map(AppSettings settings,PromptPair prompt,String requestId) throws Exception; }
    public static final class Result { public final List<EditorialDraftSceneMapper.Pair> pairs; public final String evidence; Result(List<EditorialDraftSceneMapper.Pair> pairs,String evidence){this.pairs=pairs;this.evidence=evidence;} }
    public static Result map(AppSettings settings,EditorialSceneSegmenter.Plan rawPlan,String draft,Client client,String requestPrefix)throws Exception{
        EditorialRawMap draftMap=EditorialRawMap.create(draft);String draftIndex=index(draftMap);ArrayList<EditorialDraftSceneMapper.Pair> pairs=new ArrayList<>();org.json.JSONArray evidence=new org.json.JSONArray();int cursor=0;
        for(int i=0;i<rawPlan.scenes.size();i++){EditorialSceneSegmenter.Scene scene=rawPlan.scenes.get(i);String system="Map one RAW scene to DRAFT anchors. Do not audit or rewrite. Return only JSON: {\"sceneId\":\"exact\",\"rawStart\":\"exact\",\"rawEnd\":\"exact\",\"draftStart\":\"d000001\",\"draftEnd\":\"d000002\",\"status\":\"ALIGNED|MISSING\"}. Mapping must continue monotonically from the required next DRAFT anchor.";String user="SCENE: "+scene.id+"\nRAW: "+scene.startAnchor+" -> "+scene.endAnchor+"\nREQUIRED NEXT DRAFT ANCHOR: "+draftId(cursor+1)+"\nRAW SCENE:\n"+scene.raw+"\nDRAFT ANCHOR INDEX:\n"+draftIndex;OpenAICompatibleClient.ChatResult response=client.map(settings,new PromptPair(system,user),requestPrefix+":"+scene.id);JSONObject row=new JSONObject(response.content);row.put("promptTokens",response.promptTokens).put("completionTokens",response.completionTokens).put("totalTokens",response.totalTokens);if(!scene.id.equals(row.optString("sceneId"))||!scene.startAnchor.equals(row.optString("rawStart"))||!scene.endAnchor.equals(row.optString("rawEnd")))throw new IllegalArgumentException("Mapping RAW anchors do not match "+scene.id);String status=row.optString("status");if("MISSING".equals(status)){pairs.add(new EditorialDraftSceneMapper.Pair(i+1,scene.raw,"",scene.startAnchor,scene.endAnchor,EditorialDraftSceneMapper.Status.ALIGNED));evidence.put(row);continue;}if(!"ALIGNED".equals(status))throw new IllegalArgumentException("Invalid mapping status for "+scene.id);int start=parseDraft(row.optString("draftStart")),end=parseDraft(row.optString("draftEnd"));if(start!=cursor+1||end<start||end>draftMap.anchors.size())throw new IllegalArgumentException("Non-monotonic DRAFT mapping at "+scene.id);StringBuilder mapped=new StringBuilder();for(int a=start-1;a<end;a++)mapped.append(draftMap.anchors.get(a).text);cursor=end;pairs.add(new EditorialDraftSceneMapper.Pair(i+1,scene.raw,mapped.toString(),scene.startAnchor,scene.endAnchor,EditorialDraftSceneMapper.Status.ALIGNED));evidence.put(row);}
        if(cursor!=draftMap.anchors.size())throw new IllegalArgumentException("Model mapping did not cover DRAFT through final anchor");return new Result(pairs,evidence.toString());
    }
    private static String index(EditorialRawMap map){StringBuilder out=new StringBuilder();for(int i=0;i<map.anchors.size();i++){String text=map.anchors.get(i).text.replace('\n',' ').trim();if(text.length()>120)text=text.substring(0,120);out.append(draftId(i+1)).append(": ").append(text).append('\n');}if(out.length()>12000)throw new IllegalArgumentException("DRAFT anchor index exceeds safe mapping context");return out.toString();}
    private static int parseDraft(String id){if(id==null||!id.matches("d\\d{6}"))throw new IllegalArgumentException("Invalid DRAFT anchor");return Integer.parseInt(id.substring(1));}private static String draftId(int n){return String.format(java.util.Locale.US,"d%06d",n);}
    private EditorialModelSceneMapper(){}
}
