package com.ml.tblandroidtxt;
/** Creates two unrelated prompt packages; REPORT_L1 exists only in the second package. */
public final class EditorialL3ContextBuilder {
 public static PromptPair independent(long chapterId,String raw,String viL2,String glossary,String pronoun){String system="Independent L3 QA of Japanese RAW against VI_L2. You cannot see REPORT_L1, L1 reasoning, L2 prompts or L2 reasoning. Build a fresh scene ledger and compare RAW to VI_L2 sequentially. Return only JSON matching: "+EditorialL3IndependentContract.schema();String user="CHAPTER: "+chapterId+"\nGLOSSARY:\n"+glossary+"\nPRONOUN:\n"+pronoun+"\nRAW:\n"+raw+"\nVI_L2:\n"+viL2+"\nClose coverage, fidelity, voice and cross-scene voice audit before returning.";return new PromptPair(system,user);}
 public static PromptPair reportReview(long chapterId,String raw,String viL2,String glossary,String pronoun,String independentEvidence,String reportL1){if(EditorialL3IndependentContract.validate(independentEvidence,String.valueOf(chapterId))!=null)throw new IllegalArgumentException("Closed independent L3 evidence is required before REPORT_L1");String system="Final L3 QA. Independent RAW–VI_L2 comparison is already closed and immutable. Now review REPORT_L1 only as secondary evidence. Return only JSON matching: "+EditorialEvidenceSchema.l3OutputSchema();String user="CHAPTER: "+chapterId+"\nCLOSED INDEPENDENT EVIDENCE:\n"+independentEvidence+"\nGLOSSARY:\n"+glossary+"\nPRONOUN:\n"+pronoun+"\nRAW:\n"+raw+"\nVI_L2:\n"+viL2+"\nREPORT_L1 (opened only after independent checkpoint):\n"+reportL1+"\nOutput complete FINAL_QA, Change Set, close cross-scene voice audit and final read-through.";return new PromptPair(system,user);}
 public static PromptPair independentScene(long chapterId,EditorialSceneSegmenter.Scene scene,String viScene,String glossary,String pronoun){String system="Independent L3 QA for exactly one scene. You cannot see REPORT_L1 or prior model reasoning. Compare RAW to VI_L2 and return only JSON matching: "+EditorialL3IndependentContract.schema();String user="CHAPTER: "+chapterId+"\nEXPECTED SCENE: "+scene.id+" | "+scene.startAnchor+" -> "+scene.endAnchor+"\nGLOSSARY:\n"+glossary+"\nPRONOUN:\n"+pronoun+"\nRAW SCENE:\n"+scene.raw+"\nVI_L2 SCENE:\n"+viScene;return new PromptPair(system,user);}
 public static PromptPair finalScene(long chapterId,EditorialSceneSegmenter.Scene scene,String viScene,String glossary,String pronoun,String independentScene,String reportScene){String system="Final L3 QA for exactly one scene. Independent RAW–VI_L2 evidence is closed. REPORT_L1 is secondary evidence. Return only JSON matching: "+EditorialL3SceneContract.schema();String user="CHAPTER: "+chapterId+"\nSCENE: "+scene.id+"\nEXPECTED RAW ANCHORS: "+scene.startAnchor+" -> "+scene.endAnchor+"\nCLOSED INDEPENDENT EVIDENCE:\n"+independentScene+"\nGLOSSARY:\n"+glossary+"\nPRONOUN:\n"+pronoun+"\nRAW SCENE:\n"+scene.raw+"\nVI_L2 SCENE:\n"+viScene+"\nREPORT_L1 SCENE EVIDENCE:\n"+reportScene+"\nReturn complete FINAL_QA scene and close every gate/read-through.";return new PromptPair(system,user);}
 public static PromptPair voiceAudit(long chapterId,String independentLedger,String pronoun){String system="Independent chapter-level cross-scene voice audit. You cannot see REPORT_L1 or prior model reasoning. Synthesize only the closed per-scene RAW–VI_L2 evidence. Return only JSON matching: "+EditorialL3VoiceAuditContract.schema();String user="CHAPTER: "+chapterId+"\nPRONOUN/VOICE RULES:\n"+pronoun+"\nCLOSED INDEPENDENT SCENE LEDGER:\n"+independentLedger+"\nCheck voice consistency across all listed scenes and close the audit.";return new PromptPair(system,user);}
 private EditorialL3ContextBuilder(){}
}
