package com.ml.tblandroidtxt;

public enum EditorialPackImportError {
    NONE,
    NULL_INPUT,
    ENTRY_COUNT_LIMIT,
    INVALID_ENTRY_PATH,
    DUPLICATE_NORMALIZED_PATH,
    SYMLINK_FORBIDDEN,
    ENTRY_SIZE_LIMIT,
    TOTAL_SIZE_LIMIT,
    COMPRESSION_RATIO_LIMIT,
    TRUNCATED_STREAM,
    SNAPSHOT_WRITE_FAILED,
    DATABASE_WRITE_FAILED,
    STORAGE_MOVE_FAILED,
    STORAGE_COLLISION,
    IDENTITY_COLLISION,
    EXISTING_STORAGE_MISSING,
    INTEGRITY_INVALID,
    COMPATIBILITY_BLOCKED,
    RECOVERY_BLOCKED,
    ZIP_INVALID
}
