package com.ml.tblandroidtxt;
import java.util.List;
/** Builds two fresh L2 contexts and enforces the RAW-first visibility barrier. */
public final class EditorialL2ContextBuilder {
 public static PromptPair rawMapping(long chapterId,List<EditorialRepository.AssetSnapshot> assets){EditorialRepository.AssetSnapshot raw=find(assets,EditorialWorkflowV5.AssetRole.RAW),g=find(assets,EditorialWorkflowV5.AssetRole.GLOSSARY),p=find(assets,EditorialWorkflowV5.AssetRole.PRONOUN);String system="Create an independent RAW-only Scene Ledger for L2. You cannot see DRAFT or REPORT_L1. Return only JSON matching: "+EditorialL2RawLedgerContract.schema();String user="CHAPTER: "+chapterId+"\nGLOSSARY:\n"+g.content+"\nPRONOUN:\n"+p.content+"\nRAW:\n"+raw.content;return new PromptPair(system,user);}
 public static PromptPair edit(long chapterId,List<EditorialRepository.AssetSnapshot> assets,String rawLedger,String reportL1){EditorialRepository.AssetSnapshot raw=find(assets,EditorialWorkflowV5.AssetRole.RAW),draft=find(assets,EditorialWorkflowV5.AssetRole.DRAFT),g=find(assets,EditorialWorkflowV5.AssetRole.GLOSSARY),p=find(assets,EditorialWorkflowV5.AssetRole.PRONOUN);if(rawLedger==null||reportL1==null)throw new IllegalArgumentException("L2 ledger and REPORT_L1 are required");String system="Edit Japanese-to-Vietnamese fiction in L2. The RAW-only ledger was completed before this context. Lock meaning from RAW first, then preserve correct DRAFT text and apply REPORT_L1 only as points to verify. Return only JSON matching: "+EditorialEvidenceSchema.l2OutputSchema();String user="CHAPTER: "+chapterId+"\nRAW-ONLY SCENE LEDGER:\n"+rawLedger+"\nGLOSSARY:\n"+g.content+"\nPRONOUN:\n"+p.content+"\nRAW:\n"+raw.content+"\nDRAFT:\n"+draft.content+"\nREPORT_L1 (verify, do not assume correct):\n"+reportL1+"\nOutput full VI_L2 and close every gate/change.";return new PromptPair(system,user);}
 public static PromptPair rawScene(long chapterId,EditorialSceneSegmenter.Scene scene,String glossary,String pronoun){String system="Create a RAW-only L2 ledger for exactly one scene. You cannot see DRAFT or REPORT_L1. Return only JSON matching: "+EditorialL2RawLedgerContract.schema();String user="CHAPTER: "+chapterId+"\nEXPECTED SCENE: "+scene.id+" | "+scene.startAnchor+" -> "+scene.endAnchor+"\nGLOSSARY:\n"+glossary+"\nPRONOUN:\n"+pronoun+"\nRAW SCENE:\n"+scene.raw;return new PromptPair(system,user);}
 public static PromptPair editScene(long chapterId,String sceneId,String rawStart,String rawEnd,String raw,String draft,String ledgerScene,String reportScene,String glossary,String pronoun){String system="Edit exactly one Japanese-to-Vietnamese fiction scene in L2. RAW-only ledger is already closed. Preserve correct DRAFT text, correct only against RAW and verified report evidence. Return only JSON matching: "+EditorialL2SceneContract.schema();String user="CHAPTER: "+chapterId+"\nSCENE: "+sceneId+"\nEXPECTED RAW ANCHORS: "+rawStart+" -> "+rawEnd+"\nCLOSED RAW LEDGER SCENE:\n"+ledgerScene+"\nGLOSSARY:\n"+glossary+"\nPRONOUN:\n"+pronoun+"\nRAW SCENE:\n"+raw+"\nDRAFT SCENE:\n"+draft+"\nREPORT_L1 SCENE EVIDENCE:\n"+reportScene+"\nReturn the complete edited scene and close every gate/change.";return new PromptPair(system,user);}
 private static EditorialRepository.AssetSnapshot find(List<EditorialRepository.AssetSnapshot> assets,EditorialWorkflowV5.AssetRole role){for(EditorialRepository.AssetSnapshot a:assets)if(a.role==role)return a;throw new IllegalArgumentException("Missing "+role);}private EditorialL2ContextBuilder(){}
}
