package com.ml.tblandroidtxt;
import org.json.JSONArray;import org.json.JSONObject;import java.util.List;
/** Two-call L2 runner. The RAW-only ledger must close before DRAFT is exposed. */
public final class EditorialL2Runner {
 public interface Client{OpenAICompatibleClient.ChatResult complete(AppSettings s,PromptPair p,String id)throws Exception;} public static final class Result{public final long runId;public final String output;Result(long id,String text){runId=id;output=text;}}
 private final EditorialRepository repo;private final Client client;public EditorialL2Runner(EditorialRepository r){this(r,(s,p,id)->OpenAICompatibleClient.chatWithUsage(s,p,s.maxOutputTokens,id));}EditorialL2Runner(EditorialRepository r,Client c){repo=r;client=c;}
 public Result run(long chapterId,AppSettings settings)throws Exception{EditorialRepository.Chapter chapter=repo.getChapter(chapterId);if(chapter==null)throw new IllegalArgumentException("Editorial chapter not found");if(chapter.state!=EditorialWorkflowV5.ChapterState.L1_CLOSED)throw new IllegalStateException("L2 requires a closed L1 machine gate");List<EditorialRepository.AssetSnapshot> assets=repo.chapterAssets(chapterId);String report=repo.latestEvidenceForChapter(chapterId,"REPORT_L1_JSON"),reportError=EditorialEvidenceValidator.validateL1Report(report);if(reportError!=null)throw new IllegalStateException("L2 blocked by REPORT_L1: "+reportError);PromptPair rawPrompt=EditorialL2ContextBuilder.rawMapping(chapterId,assets);requireSafeContext(rawPrompt,"RAW ledger");String manifest=manifest(chapterId,assets,report);long runId=repo.createRun(chapterId,"L2",settings.provider,settings.model,HashUtil.sha256(rawPrompt.system+"\n"+rawPrompt.user),HashUtil.sha256(EditorialEvidenceSchema.VERSION),manifest);repo.saveEvidence(runId,"L2_CONTEXT_MANIFEST",manifest);repo.updateRunState(runId,"RAW_MAPPING");repo.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L1_CLOSED,EditorialWorkflowV5.ChapterState.L2_READY);repo.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L2_READY,EditorialWorkflowV5.ChapterState.L2_RAW_MAPPING);EditorialWorkflowV5.ChapterState active=EditorialWorkflowV5.ChapterState.L2_RAW_MAPPING;
  try{OpenAICompatibleClient.ChatResult raw=client.complete(settings,rawPrompt,"editorial-l2:"+runId+":raw-ledger");String error=EditorialL2RawLedgerContract.validate(raw.content,String.valueOf(chapterId));if(error!=null)throw new IllegalArgumentException("L2 RAW ledger contract failed: "+error);repo.saveEvidence(runId,"L2_RAW_LEDGER",raw.content);repo.saveEvidence(runId,"L2_RAW_LEDGER_USAGE",usage(raw));repo.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L2_RAW_MAPPING,EditorialWorkflowV5.ChapterState.L2_RUNNING);active=EditorialWorkflowV5.ChapterState.L2_RUNNING;repo.updateRunState(runId,"RUNNING");PromptPair editPrompt=EditorialL2ContextBuilder.edit(chapterId,assets,raw.content,report);requireSafeContext(editPrompt,"edit");OpenAICompatibleClient.ChatResult edit=client.complete(settings,editPrompt,"editorial-l2:"+runId+":edit");error=EditorialEvidenceValidator.validateL2Output(edit.content);if(error!=null)throw new IllegalArgumentException("L2 output contract failed: "+error);JSONObject root=new JSONObject(edit.content);if(!String.valueOf(chapterId).equals(root.optString("chapterId")))throw new IllegalArgumentException("L2 output chapterId does not match run");persistGates(runId,root.getJSONObject("gates"));repo.saveEvidence(runId,"GLOBAL_CHANGE_REGISTER",root.getJSONArray("globalChanges").toString());repo.saveEvidence(runId,"VI_L2_JSON",edit.content);repo.saveEvidence(runId,"VI_L2_TEXT",root.getString("output"));repo.saveEvidence(runId,"L2_EDIT_USAGE",usage(edit));repo.updateRunState(runId,"CLOSED");repo.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L2_RUNNING,EditorialWorkflowV5.ChapterState.L2_CLOSED);return new Result(runId,root.getString("output"));}
  catch(Exception e){repo.saveEvidence(runId,"L2_FAILURE",new JSONObject().put("phase",active.name()).put("message",String.valueOf(e.getMessage())).toString());repo.updateRunState(runId,"FAILED");repo.transitionChapter(chapterId,active,EditorialWorkflowV5.ChapterState.FAILED);throw e;}}
 private void persistGates(long id,JSONObject g){save(id,EditorialWorkflowV5.Gate.COVERAGE,g,"coverage");save(id,EditorialWorkflowV5.Gate.FIDELITY,g,"fidelity");save(id,EditorialWorkflowV5.Gate.REFERENCE_VOICE,g,"referenceVoice");save(id,EditorialWorkflowV5.Gate.CONTINUITY_STRUCTURE,g,"continuityStructure");save(id,EditorialWorkflowV5.Gate.CHANGE,g,"change");}private void save(long id,EditorialWorkflowV5.Gate gate,JSONObject g,String key){repo.saveGate(id,gate,EditorialWorkflowV5.GateStatus.valueOf(g.optString(key)),g.toString());}
 private static void requireSafeContext(PromptPair p,String phase){if(p.system.length()+p.user.length()>EditorialL1ContextBuilder.MAX_INLINE_SOURCE_CHARS)throw new IllegalStateException("L2 "+phase+" exceeds safe context; segmented L2 is required");}private static String manifest(long id,List<EditorialRepository.AssetSnapshot> assets,String report)throws Exception{JSONArray rows=new JSONArray();for(EditorialRepository.AssetSnapshot a:assets)rows.put(new JSONObject().put("role",a.role.name()).put("sha256",a.sha256));return new JSONObject().put("chapterId",String.valueOf(id)).put("rawFirst",true).put("assets",rows).put("reportL1Hash",HashUtil.sha256(report)).toString();}private static String usage(OpenAICompatibleClient.ChatResult r)throws Exception{return new JSONObject().put("promptTokens",r.promptTokens).put("completionTokens",r.completionTokens).put("totalTokens",r.totalTokens).put("finishReason",r.finishReason).put("responseId",r.providerResponseId).toString();}
}
