package com.ml.tblandroidtxt;

import org.json.JSONArray;
import org.json.JSONObject;
import java.util.List;

/** Transaction-like L1 job runner: it creates a resumable run record before one isolated model call. */
public final class EditorialL1Runner {
    public interface Client { OpenAICompatibleClient.ChatResult audit(AppSettings settings,PromptPair prompt,String requestId) throws Exception; }
    public static final class Result { public final long runId; public final String report; Result(long runId,String report){this.runId=runId;this.report=report;} }
    private final EditorialRepository repository; private final Client client;
    public EditorialL1Runner(EditorialRepository repository){this(repository,(s,p,id)->OpenAICompatibleClient.chatWithUsage(s,p,s.maxOutputTokens,id));}
    EditorialL1Runner(EditorialRepository repository,Client client){this.repository=repository;this.client=client;}
    public Result run(long chapterId,AppSettings settings) throws Exception {
        EditorialRepository.Chapter chapter=repository.getChapter(chapterId);if(chapter==null)throw new IllegalArgumentException("Editorial chapter not found");if(chapter.state!=EditorialWorkflowV5.ChapterState.L1_READY)throw new IllegalStateException("L1 is not ready for this chapter");
        EditorialL1ContextBuilder.Context context=EditorialL1ContextBuilder.build(chapterId,repository.chapterAssets(chapterId));String promptHash=HashUtil.sha256(context.prompt.system+"\n"+context.prompt.user);long runId=repository.createRun(chapterId,"L1",settings.provider,settings.model,promptHash,HashUtil.sha256(EditorialEvidenceSchema.VERSION),context.manifestJson);
        repository.saveEvidence(runId,"RAW_MAP",context.rawMapJson);repository.saveEvidence(runId,"L1_CONTEXT_MANIFEST",context.manifestJson);repository.updateRunState(runId,"RUNNING");repository.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L1_READY,EditorialWorkflowV5.ChapterState.L1_RUNNING);
        try { OpenAICompatibleClient.ChatResult response=client.audit(settings,context.prompt,"editorial-l1:"+runId);String error=EditorialEvidenceValidator.validateL1Report(response.content);if(error!=null)throw new IllegalArgumentException("L1 output contract failed: "+error);JSONObject root=new JSONObject(response.content);if(!String.valueOf(chapterId).equals(root.optString("chapterId")))throw new IllegalArgumentException("L1 output chapterId does not match run");
            persistScenesAndGates(runId,root);String report=render(root);repository.saveEvidence(runId,"REPORT_L1_JSON",response.content);repository.saveEvidence(runId,"REPORT_L1_TEXT",report);repository.saveEvidence(runId,"L1_USAGE",usage(response));repository.updateRunState(runId,"CLOSED");repository.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L1_RUNNING,EditorialWorkflowV5.ChapterState.L1_CLOSED);return new Result(runId,report);
        } catch(Exception error) { repository.updateRunState(runId,"FAILED");repository.transitionChapter(chapterId,EditorialWorkflowV5.ChapterState.L1_RUNNING,EditorialWorkflowV5.ChapterState.FAILED);throw error; }
    }
    private void persistScenesAndGates(long runId,JSONObject root) throws Exception {JSONArray scenes=root.getJSONArray("scenes");for(int i=0;i<scenes.length();i++){JSONObject scene=scenes.getJSONObject(i);repository.saveScene(runId,scene.getString("id"),scene.getString("rawStart"),scene.getString("rawEnd"),scene.getString("status"),scene.toString());}JSONObject gates=root.getJSONObject("gates");repository.saveGate(runId,EditorialWorkflowV5.Gate.COVERAGE,EditorialWorkflowV5.GateStatus.valueOf(gates.getString("coverage")),gates.toString());repository.saveGate(runId,EditorialWorkflowV5.Gate.FIDELITY,EditorialWorkflowV5.GateStatus.valueOf(gates.getString("fidelity")),gates.toString());repository.saveGate(runId,EditorialWorkflowV5.Gate.REFERENCE_VOICE,EditorialWorkflowV5.GateStatus.valueOf(gates.getString("referenceVoice")),gates.toString());repository.saveGate(runId,EditorialWorkflowV5.Gate.CONTINUITY_STRUCTURE,EditorialWorkflowV5.GateStatus.valueOf(gates.getString("continuityStructure")),gates.toString());}
    private static String render(JSONObject root) throws Exception {StringBuilder out=new StringBuilder("REPORT_L1\n\nA. Scope\nChapter: ").append(root.optString("chapterId")).append("\n\nB. Scene Ledger\n");JSONArray scenes=root.getJSONArray("scenes");for(int i=0;i<scenes.length();i++){JSONObject s=scenes.getJSONObject(i);out.append("- ").append(s.optString("id")).append(" | ").append(s.optString("rawStart")).append(" → ").append(s.optString("rawEnd")).append(" | ").append(s.optString("coverage")).append("\n");}out.append("\nC. Error Ledger\n");JSONArray issues=root.getJSONArray("issues");if(issues.length()==0)out.append("No reportable deviations.\n");for(int i=0;i<issues.length();i++){JSONObject x=issues.getJSONObject(i);out.append("- ").append(x.optString("id")).append(" [").append(x.optString("severity")).append(" / ").append(x.optString("category")).append("]\n  Raw: ").append(x.optString("rawAnchor")).append("\n  Draft: ").append(x.optString("draftAnchor")).append("\n  Current: ").append(x.optString("currentMeaning")).append("\n  Raw evidence: ").append(x.optString("rawEvidence")).append("\n  Impact: ").append(x.optString("deviationImpact")).append("\n  L2 scope: ").append(x.optString("l2Scope")).append("\n");}return out.toString();}
    private static String usage(OpenAICompatibleClient.ChatResult r) throws Exception {return new JSONObject().put("promptTokens",r.promptTokens).put("completionTokens",r.completionTokens).put("totalTokens",r.totalTokens).put("finishReason",r.finishReason).put("responseId",r.providerResponseId).toString();}
}
