plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ml.tblandroidtxt'
    compileSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId 'com.ml.tblandroidtxt'
        minSdk 26
        targetSdk 35
        versionCode 46
        versionName '4.7'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "TranslateBooks-v${variant.versionName}-${variant.buildType.name}.apk"
        }
    }
}


dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20250517'
    androidTestImplementation 'androidx.test:core:1.6.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
}
