package com.ml.tblandroidtxt;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import static org.junit.Assert.*;

public class ReliabilityV43Test {
    @Rule public TemporaryFolder temp=new TemporaryFolder();
    private AppSettings charSettings(int hard){AppSettings s=new AppSettings();s.chunkMode="char";s.maxCharsPerChunk=hard;s.softLimitRatio=.7f;s.contextOverlapEnabled=false;return s;}

    @Test public void chunkCoverageHasNoGapsOverlapsAndReconstructsNormalizedSource(){String raw="第一段。\r\n\r\n第二段！\n第三段？";String normalized=Chunker.normalizeSource(raw);List<Chunk>chunks=Chunker.chunkText(raw,charSettings(9));assertTrue(Chunker.verifyCoverage(normalized,chunks).valid);StringBuilder b=new StringBuilder();int cursor=0;for(Chunk c:chunks){assertEquals(cursor,c.startOffset);b.append(c.mainContent);cursor=c.endOffset;}assertEquals(normalized,b.toString());assertEquals(normalized.length(),cursor);}
    @Test public void boundariesAreUnicodeCombiningAndDialogueSafe(){String text="開始。「これは非常に長い会話です。途中で切らないでください。」終わり😀e\u0301。";List<Chunk>cs=Chunker.chunkText(text,charSettings(12));assertTrue(Chunker.verifyCoverage(text,cs).valid);for(Chunk c:cs){if(c.endOffset<text.length()){assertFalse(Character.isHighSurrogate(text.charAt(c.endOffset-1)));assertFalse(Character.getType(text.codePointAt(c.endOffset))==Character.NON_SPACING_MARK);}assertEquals(count(c.mainContent,'「'),count(c.mainContent,'」'));}}
    @Test public void codeAndYamlBlocksAreNotSplit(){String text="---\ntitle: sample\nitems:\n - one\n - two\n---\n\n```java\nlong value = 123456789;\n```\nend";List<Chunk>cs=Chunker.chunkText(text,charSettings(10));for(Chunk c:cs){assertEquals(countText(c.mainContent,"```" )%2,0);assertEquals(countText(c.mainContent,"---")%2,0);}assertTrue(Chunker.verifyCoverage(text,cs).valid);}
    @Test public void optionalOverlapNeverEntersMainCoverage(){AppSettings s=charSettings(8);s.contextOverlapEnabled=true;s.contextChars=4;String text="abcdefgh ijklmnop qrstuvwx";List<Chunk>cs=Chunker.chunkText(text,s);StringBuilder main=new StringBuilder();for(Chunk c:cs)main.append(c.mainContent);assertEquals(text,main.toString());assertFalse(cs.get(1).contextBefore.isEmpty());}
    @Test public void rejectsEmptyWhitespaceFenceAndLength(){assertFalse(validate("","").accepted);assertFalse(validate("   ","   ").accepted);assertFalse(validate("```","```").accepted);assertFalse(ResponseValidator.validate("translated","translated","日本語","","length",10,100,false).accepted);}
    @Test public void finishReasonsAndTruncationAreClassified(){assertEquals(ResponseValidator.Finish.STOP,ResponseValidator.parseFinish("stop"));assertEquals(ResponseValidator.Finish.CONTENT_FILTER,ResponseValidator.parseFinish("content_filter"));assertFalse(ResponseValidator.validate("unfinished (text","unfinished (text","日本語","","stop",12,100,false).accepted);}
    @Test public void retryClassificationAndRetryAfter(){assertEquals(RetryPolicy.Kind.PROVIDER,RetryPolicy.classify(new ApiHttpException(503,0,"temporary")));assertEquals(RetryPolicy.Kind.NON_RETRYABLE,RetryPolicy.classify(new ApiHttpException(402,0,"credits")));assertEquals(2500,RetryPolicy.parseRetryAfterMs("2.5",0));assertTrue(RetryPolicy.backoffMs(RetryPolicy.Kind.NETWORK,3)>RetryPolicy.backoffMs(RetryPolicy.Kind.NETWORK,1));}
    @Test public void contextOverflowCreatesOrderedStableChildren(){AppSettings s=charSettings(200);String source="段落一。段落二。段落三。段落四。段落五。段落六。";Chunk parent=new Chunk(2,100,100+source.length(),"",source,"","");List<Chunk>children=Chunker.splitForContextOverflow(parent,s);assertTrue(children.size()>=2);int cursor=100;StringBuilder b=new StringBuilder();for(Chunk c:children){assertEquals(parent.stableId,c.parentStableId);assertEquals(cursor,c.startOffset);cursor=c.endOffset;b.append(c.mainContent);}assertEquals(source,b.toString());}
    @Test public void qaAndIntegrityDetectDuplicatesAndIncompleteRows(){ChunkQa.Metrics qa=ChunkQa.inspect("a\nb\nc","same\nsame\nsame\nsame","");assertTrue(qa.warnings.contains("REPEATED_BLOCK"));List<TranslationRepository.ChunkRow>rows=new ArrayList<>();rows.add(row(0,"a","A","COMPLETED",0,1));rows.add(row(1,"b","A","COMPLETED",1,2));OutputIntegrityAudit.Result audit=OutputIntegrityAudit.audit(rows);assertTrue(audit.passed());assertTrue(audit.warnings.toString().contains("DUPLICATE_ADJACENT"));rows.get(1).status="RETRYABLE_ERROR";assertFalse(OutputIntegrityAudit.audit(rows).passed());}
    @Test public void atomicCommitKeepsBackupAndRejectsEmpty() throws Exception {Path p=temp.newFile("out.txt").toPath();java.nio.file.Files.write(p,"old".getBytes(java.nio.charset.StandardCharsets.UTF_8));AtomicFileCommit.Result result=AtomicFileCommit.write(p,"new value");assertEquals("new value",read(p));assertNotNull(result.backup);assertEquals("old",read(result.backup));try{AtomicFileCommit.write(p,"");fail();}catch(IllegalArgumentException expected){}assertEquals("new value",read(p));}
    @Test public void resumeGuardDetectsChangedInput(){String hash=HashUtil.sha256("book");assertEquals("OK",ResumeGuard.verifyInput(hash,"book"));assertEquals("INPUT_HASH_MISMATCH",ResumeGuard.verifyInput(hash,"changed"));}
    @Test public void budgetStopsBeforeNextRequestButNotCurrentCommit(){AppSettings s=new AppSettings();s.stopOnCostLimit=true;s.costLimitUsd=1;assertTrue(BudgetPolicy.beforePaidRequest(s,.9,0,0,true).allowed);assertFalse(BudgetPolicy.beforePaidRequest(s,1.01,0,0,true).allowed);s.stopWhenPricingUnknown=true;assertEquals("PRICING_UNKNOWN",BudgetPolicy.beforePaidRequest(s,0,0,0,false).reason);}
    @Test public void settingsSnapshotIsImmutableAndIncludesReliabilityFields(){AppSettings s=new AppSettings();s.model="provider/original";s.contextOverlapEnabled=true;s.maxRetryDelayMs=9000;String json=SettingsStore.toJson(s);s.model="provider/changed";AppSettings snapshot=SettingsStore.fromJson(json);assertEquals("provider/original",snapshot.model);assertTrue(snapshot.contextOverlapEnabled);assertEquals(9000,snapshot.maxRetryDelayMs);}
    @Test public void migrationSpecIsNonDestructiveAndAddsRequiredTables(){String sql=String.join("\n",DatabaseMigrationSpec.from42To43()).toLowerCase();assertTrue(sql.contains("stable_id"));assertTrue(sql.contains("chunk_attempts"));assertTrue(sql.contains("config_revisions"));assertFalse(sql.contains("drop table"));assertFalse(sql.contains("delete from"));}

    private ResponseValidator.Result validate(String raw,String out){return ResponseValidator.validate(raw,out,"日本語","","stop",1,100,false);}private int count(String s,char x){int n=0;for(char c:s.toCharArray())if(c==x)n++;return n;}private int countText(String s,String x){int n=0,p=0;while((p=s.indexOf(x,p))>=0){n++;p+=x.length();}return n;}
    private TranslationRepository.ChunkRow row(int i,String src,String out,String status,int start,int end){TranslationRepository.ChunkRow r=new TranslationRepository.ChunkRow();r.index=i;r.source=src;r.translated=out;r.status=status;r.startOffset=start;r.endOffset=end;r.sourceHash=HashUtil.sha256(src);r.rejectedResponse="";return r;}
    private String read(Path p)throws Exception{return new String(java.nio.file.Files.readAllBytes(p),java.nio.charset.StandardCharsets.UTF_8);}
}
