package com.ml.tblandroidtxt;

import static org.junit.Assert.*;
import androidx.test.core.app.ApplicationProvider;
import org.junit.Test;

public class EditorialProjectFolderInstrumentedTest {
    @Test public void releaseFolderPersistsOnlyOnTargetProject(){EditorialRepository repo=new EditorialRepository(ApplicationProvider.getApplicationContext());long first=-1,second=-1;try{EditorialRepository.Project a=new EditorialRepository.Project();a.seriesName="QA Folder A "+System.nanoTime();a.volumeName="V";a.workflowHash=HashUtil.sha256("w");first=repo.createProject(a);EditorialRepository.Project b=new EditorialRepository.Project();b.seriesName="QA Folder B "+System.nanoTime();b.volumeName="V";b.workflowHash=HashUtil.sha256("w");second=repo.createProject(b);repo.updateProjectOutputTree(first,"content://qa/tree/release");assertEquals("content://qa/tree/release",repo.getProject(first).outputTreeUri);assertTrue(repo.getProject(second).outputTreeUri.isEmpty());}finally{if(first>0)repo.deleteProject(first);if(second>0)repo.deleteProject(second);repo.close();}}

    @Test public void editorialReferencesAndIdentityAreProjectOwned(){EditorialRepository repo=new EditorialRepository(ApplicationProvider.getApplicationContext());long first=-1,second=-1;try{String nonce=String.valueOf(System.nanoTime());EditorialRepository.Project a=new EditorialRepository.Project();a.seriesName="QA Ref A "+nonce;a.volumeName="V1";a.workflowHash=HashUtil.sha256("w");first=repo.createProject(a);EditorialRepository.Project b=new EditorialRepository.Project();b.seriesName="QA Ref B "+nonce;b.volumeName="V2";b.workflowHash=HashUtil.sha256("w");second=repo.createProject(b);repo.saveProjectReference(first,new EditorialRepository.AssetSnapshot(EditorialWorkflowV5.AssetRole.GLOSSARY,"content://qa/g","g.txt","term=value"));repo.saveProjectReference(first,new EditorialRepository.AssetSnapshot(EditorialWorkflowV5.AssetRole.PRONOUN,"content://qa/p","p.txt","a=b"));assertEquals("term=value",repo.projectReference(first,EditorialWorkflowV5.AssetRole.GLOSSARY).content);assertNull(repo.projectReference(second,EditorialWorkflowV5.AssetRole.GLOSSARY));repo.updateProjectIdentity(first,"QA Ref Renamed "+nonce,"Vol 9");assertEquals("QA Ref Renamed "+nonce,repo.getProject(first).seriesName);assertEquals("Vol 9",repo.getProject(first).volumeName);}finally{if(first>0)repo.deleteProject(first);if(second>0)repo.deleteProject(second);repo.close();}}
}
