[CmdletBinding()]
param([string]$OutputPath = '')
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
if ([string]::IsNullOrWhiteSpace($OutputPath)) { $OutputPath = Join-Path $repoRoot 'docs\P5E_A43_PREAUTH_RUNTIME_GUARD_CLOSURE_QA_20260928.json' }
$ps51Path = 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
$helperPath = Join-Path $repoRoot 'scripts\p5e-raw-live-supervisor.ps1'
$exporterPath = Join-Path $repoRoot 'scripts\p5e-db-binary-export.ps1'
$guardPath = Join-Path $repoRoot 'scripts\p5e-a43-runtime-guards.ps1'
$toolchainPath = Join-Path $repoRoot 'scripts\p5e-raw-toolchain.ps1'
$bridgePath = Join-Path $repoRoot 'docs\P5E_SQLITE_BRIDGE.py'
$manifestPath = Join-Path $repoRoot 'docs\P5E_A43_DECISION_ATOMICITY_EXPECTED_ENV_ISOLATION_MANIFEST_20260928.md'
$commandPath = Join-Path $repoRoot 'docs\P5E_A43_DECISION_ATOMICITY_EXPECTED_ENV_ISOLATION_COMMAND_20260928.txt'
$oldCommandPath = Join-Path $repoRoot 'docs\P5E_A43_PM_PATH_CAPTURE_REPAIR_COMMAND_20260928.txt'
$atomicQaPath = Join-Path $repoRoot 'scripts\test-p5e-a43-decision-atomicity-expected-env.ps1'
$bindingQaPath = Join-Path $repoRoot 'scripts\test-p5e-a43-binding-tuple-matrix.ps1'
$dbQaPath = Join-Path $repoRoot 'scripts\test-p5e-a43-db-host-readback-matrix.ps1'
$serial = '15e84958'
$scope = 'RAW/GLOSSARY'
$packetIdentifier = 'P5E-A43-DECISION-ATOMICITY-ENV-20260928-01'
$stdoutLimit = 4194304
$stderrLimit = 1048576
$tests = [System.Collections.Generic.List[object]]::new()
$matrixEvidence = [ordered]@{
    atomicityExpectedEnvironment = [ordered]@{ status = 'NOT_RUN'; testCount = 0; passedTestCount = 0; highFailureCount = 0 }
    binding = [ordered]@{ status = 'NOT_RUN'; testCount = 0; passedTestCount = 0 }
    regression = [ordered]@{ status = 'NOT_RUN'; caseCount = 0; passedCaseCount = 0 }
    dbHostReadback = [ordered]@{ status = 'NOT_RUN'; testCount = 0; passedTestCount = 0; failureCount = 0 }
    powershell51Parse = [ordered]@{ status = 'NOT_RUN' }
    gitDiffCheck = [ordered]@{ status = 'NOT_RUN' }
}
$runtimeEvidence = [ordered]@{
    suspendedJobLaunch = [ordered]@{ status = 'NOT_RUN'; containmentAttachedBeforeResume = $false; childDescendantVerification = 'NOT_RUN' }
    drainFailure = [ordered]@{ status = 'NOT_RUN'; processExitCode = $null; captureErrorClass = ''; stdoutDrainStatus = ''; stderrDrainStatus = ''; captureBounded = $false; containmentVerified = $false; descendantExited = $false }
    wrapperBinding = [ordered]@{ status = 'NOT_RUN'; captureErrorChecked = $false; processExitPreserved = $false; typedWrapperStatus = '' }
}
$tempRoot = Join-Path ([IO.Path]::GetTempPath()) ('p5e-a43-guard-closure-' + [Guid]::NewGuid().ToString('N'))
[void](New-Item -ItemType Directory -Path $tempRoot -Force)
. $helperPath -LibraryOnly
# The library script has its own historical `$manifestPath` variable. Rebind
# the QA target after dot-sourcing so this test never hashes an older packet.
$manifestPath = Join-Path $repoRoot 'docs\P5E_A43_DECISION_ATOMICITY_EXPECTED_ENV_ISOLATION_MANIFEST_20260928.md'

function Get-HashUpper { param([Parameter(Mandatory=$true)][string]$Path) return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToUpperInvariant() }
function Add-Test { param([Parameter(Mandatory=$true)][string]$Name,[Parameter(Mandatory=$true)][bool]$Passed,[string]$Detail=''); $safe=if([string]::IsNullOrWhiteSpace($Detail)){''}else{$Detail.Split([Environment]::NewLine)[0]}; [void]$tests.Add([ordered]@{name=$Name;passed=$Passed;detail=$safe}) }
function Run-Test { param([Parameter(Mandatory=$true)][string]$Name,[Parameter(Mandatory=$true)][scriptblock]$Action); try { & $Action; Add-Test $Name $true } catch { Add-Test $Name $false ([string]$_.Exception.Message) } }
function Assert-True { param([Parameter(Mandatory=$true)][bool]$Condition,[Parameter(Mandatory=$true)][string]$Message); if(-not $Condition){throw $Message} }
function Expect-Stop { param([Parameter(Mandatory=$true)][scriptblock]$Action,[Parameter(Mandatory=$true)][string]$Code); $ok=$false; try{& $Action|Out-Null}catch{ $ok=([string]$_.Exception.Message -match [regex]::Escape($Code)) }; if(-not $ok){throw ('EXPECTED_STOP_MISMATCH:'+ $Code)} }
function ConvertTo-WindowsArgument {
    param([Parameter(Mandatory=$true)][AllowEmptyString()][string]$Value)
    if($Value.Length -gt 0 -and $Value -notmatch '[\s"]'){return $Value}
    $b=[Text.StringBuilder]::new();[void]$b.Append('"');$slashes=0
    foreach($c in $Value.ToCharArray()){if($c -eq '\'){$slashes++;continue};if($c -eq '"'){[void]$b.Append(('\'*(2*$slashes+1)));[void]$b.Append('"');$slashes=0;continue};if($slashes -gt 0){[void]$b.Append(('\'*$slashes));$slashes=0};[void]$b.Append($c)}
    if($slashes -gt 0){[void]$b.Append(('\'*(2*$slashes)))};[void]$b.Append('"');return $b.ToString()
}
function Invoke-PS51Script {
    param([Parameter(Mandatory=$true)][string]$ScriptPath,[Parameter(Mandatory=$true)][string[]]$Arguments)
    $name='P5E_OWNER_ENDPOINT_ACCOUNT_FINGERPRINT';$old=[Environment]::GetEnvironmentVariable($name,'Process');[Environment]::SetEnvironmentVariable($name,$null,'Process')
    try{& $ps51Path -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $ScriptPath @Arguments 2>&1|Out-Null;$code=$LASTEXITCODE}finally{[Environment]::SetEnvironmentVariable($name,$old,'Process')};return [int]$code
}
function New-CaptureFixtureScript {
    $p=Join-Path $tempRoot 'capture-fixture.ps1'
    $t=@'
param([string]$Mode,[int]$Count=0)
switch($Mode) {
 'stdout' {[Console]::Out.Write('stdout');break}
 'stderr' {[Console]::Error.Write('stderr');break}
 'both' {[Console]::Out.Write('stdout');[Console]::Error.Write('stderr');break}
 'empty' {break}
 'exact' {$b=New-Object byte[] $Count;[Console]::OpenStandardOutput().Write($b,0,$b.Length);break}
 'invalid' {$b=[byte[]](0xff,0xfe,0xfd);[Console]::OpenStandardOutput().Write($b,0,$b.Length);break}
 'delayed' {[Console]::Out.Write('delayed');[Console]::Out.Flush();Start-Sleep -Milliseconds 250;break}
 'secret' {[Console]::Out.Write(('qa-'+'sentinel'));break}
 'nonzero' {[Console]::Out.Write('nonzero');exit 7}
 'timeout' {Start-Sleep -Seconds 120;break}
  'tree-grandchild' {Start-Sleep -Seconds 120;break}
  'tree-child' {$grandchild=Start-Process -FilePath $env:WINDIR\System32\WindowsPowerShell\v1.0\powershell.exe -ArgumentList @('-NoLogo','-NoProfile','-NonInteractive','-File',$PSCommandPath,'tree-grandchild') -WindowStyle Hidden -PassThru;[IO.File]::AppendAllText($env:P5E_TREE_PID_FILE,[Environment]::NewLine+[string]$grandchild.Id);Start-Sleep -Seconds 120;break}
  'tree' {[IO.File]::WriteAllText($env:P5E_TREE_PID_FILE,'');$child=Start-Process -FilePath $env:WINDIR\System32\WindowsPowerShell\v1.0\powershell.exe -ArgumentList @('-NoLogo','-NoProfile','-NonInteractive','-File',$PSCommandPath,'tree-child') -WindowStyle Hidden -PassThru;[IO.File]::AppendAllText($env:P5E_TREE_PID_FILE,[string]$child.Id);$deadline=(Get-Date).AddSeconds(5);while((Get-Date)-lt $deadline -and @([IO.File]::ReadAllLines($env:P5E_TREE_PID_FILE)).Count -lt 2){Start-Sleep -Milliseconds 50};[Console]::Out.Write([string]$child.Id);[Console]::Out.Flush();Start-Sleep -Seconds 120;break}
  'drain-hold' {Start-Sleep -Milliseconds 1000;$childInfo=[Diagnostics.ProcessStartInfo]::new();$childInfo.FileName=$env:WINDIR+'\System32\WindowsPowerShell\v1.0\powershell.exe';$childInfo.UseShellExecute=$false;$childInfo.CreateNoWindow=$true;$childInfo.Arguments='-NoLogo -NoProfile -NonInteractive -Command "Start-Sleep -Seconds 120"';$child=[Diagnostics.Process]::Start($childInfo);[IO.File]::WriteAllText($env:P5E_TREE_PID_FILE,[string]$child.Id);[Console]::Out.Write('drain-hold');[Console]::Out.Flush();exit 0}
}
'@
    [IO.File]::WriteAllText($p,$t,[Text.UTF8Encoding]::new($false));return $p
}
function Invoke-TextCaptureFixture {
    param([Parameter(Mandatory=$true)][string]$ScriptPath,[Parameter(Mandatory=$true)][string]$Mode,[int]$OutLimit=$stdoutLimit,[int]$ErrLimit=$stderrLimit,[int]$Timeout=5000,[int]$Count=0)
    $si=[Diagnostics.ProcessStartInfo]::new();$si.FileName=$ps51Path;$si.UseShellExecute=$false;$si.CreateNoWindow=$true;$si.RedirectStandardOutput=$true;$si.RedirectStandardError=$true
    $treePidFile=Join-Path $tempRoot ('tree-pids-'+[Guid]::NewGuid().ToString('N')+'.txt');$si.EnvironmentVariables['P5E_TREE_PID_FILE']=$treePidFile
    $args=@('-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$ScriptPath,$Mode,[string]$Count);$si.Arguments=[string]::Join(' ',@($args|ForEach-Object{ConvertTo-WindowsArgument ([string]$_)}))
    $p=$null;$launch=$null
    try{$launch=[P5EProcessLauncher]::Start($si);$p=$launch.Process;$c=[P5EProcessTextCapture]::Capture($launch,$OutLimit,$ErrLimit,$Timeout,$null);return [pscustomobject]@{ExitCode=$c.ExitCode;CaptureBounded=[bool]$c.CaptureBounded;ContainmentVerified=[bool]$c.ContainmentVerified;ContainmentStatus=[string]$c.ContainmentStatus;CaptureErrorClass=[string]$c.CaptureErrorClass;StdoutDrainStatus=[string]$c.StdoutDrainStatus;StderrDrainStatus=[string]$c.StderrDrainStatus;TimedOut=[bool]$c.TimedOut;OutputTooLarge=[bool]$c.OutputTooLarge;StdoutTruncated=[bool]$c.StdoutTruncated;StderrTruncated=[bool]$c.StderrTruncated;StdoutByteLength=[long]$c.StdoutByteLength;StderrByteLength=[long]$c.StderrByteLength;StdoutText=[string]$c.Stdout;TreePidFile=$treePidFile;SecretWasCapturedInMemory=([string]$c.Stdout -match 'qa-sentinel')}}finally{if($null-ne$launch){$launch.Dispose()}elseif($null-ne$p){$p.Dispose()}}
}
function New-ReceiptObject {
    param([long]$IssuedAt=0L,[long]$ExpiresAt=0L)
    if($IssuedAt -eq 0L){$IssuedAt=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()-1000L};if($ExpiresAt -eq 0L){$ExpiresAt=$IssuedAt+60000L}
    return [ordered]@{schemaVersion='p5e.a43.owner-decision-receipt.v1';decisionId='qa-guard-decision-01';packetIdentifier=$packetIdentifier;serial=$serial;manifestSha256=(Get-HashUpper $manifestPath);commandSha256=(Get-HashUpper $commandPath);helperSha256=(Get-HashUpper $helperPath);exporterSha256=(Get-HashUpper $exporterPath);bridgeSha256=(Get-HashUpper $bridgePath);oneEventLimit=1;oneProviderCallLimit=1;scope=$scope;noRetry=$true;noFallback=$true;noRedispatch=$true;issuedAt=$IssuedAt;expiresAt=$ExpiresAt}
}
function Write-ReceiptFixture { param([Parameter(Mandatory=$true)]$Receipt,[string]$Name='');if([string]::IsNullOrWhiteSpace($Name)){$Name=[Guid]::NewGuid().ToString('N')};$p=Join-Path $tempRoot ('receipt-'+$Name+'.json');[IO.File]::WriteAllText($p,($Receipt|ConvertTo-Json -Depth 10),[Text.UTF8Encoding]::new($false));return [pscustomobject]@{Path=$p;Hash=(Get-HashUpper $p)} }
function Assert-ReceiptFixture { param([Parameter(Mandatory=$true)]$Fixture,[string]$ExpectedCode='');$pins=@{manifestSha256=(Get-HashUpper $manifestPath);commandSha256=(Get-HashUpper $commandPath);helperSha256=(Get-HashUpper $helperPath);exporterSha256=(Get-HashUpper $exporterPath);bridgeSha256=(Get-HashUpper $bridgePath)};$a={Read-P5EA43OwnerDecisionReceipt -ReceiptPath $Fixture.Path -ExpectedReceiptSha256 $Fixture.Hash -ExpectedPins $pins -ExpectedSerial $serial -ExpectedScope $scope};if([string]::IsNullOrWhiteSpace($ExpectedCode)){return & $a};Expect-Stop $a $ExpectedCode}

$fixtureScript=New-CaptureFixtureScript;$oldCommandText=Get-Content -Raw $oldCommandPath;$newCommandText=Get-Content -Raw $commandPath;$manifestText=Get-Content -Raw $manifestPath

Run-Test 'RED-1-old-wrapper-masks-known-exit-when-drain-fails' {Assert-True ($oldCommandText.IndexOf('$process.Kill($true)',[StringComparison]::Ordinal)-ge 0) 'OLD_TREE_KILL_BOOL_OVERLOAD_NOT_REPRODUCED';$s=[pscustomobject]@{processExitCode=7;stdoutDrainStatus='TIMEOUT';wrapperExitCode=125};Assert-True ($s.processExitCode-eq 7-and$s.wrapperExitCode-eq 125-and$s.stdoutDrainStatus-eq 'TIMEOUT') 'RED_MASKING_FIXTURE_INVALID'}
Run-Test 'RED-2-old-command-creates-event-before-owner-gate' {$i=$oldCommandText.IndexOf('[void](New-Item -ItemType Directory',[StringComparison]::Ordinal);Assert-True ($i-ge 0-and$oldCommandText.IndexOf('P5E_OWNER_DECISION_RECEIPT_PATH',[StringComparison]::Ordinal)-lt 0) 'OLD_PREAUTH_ORDER_NOT_REPRODUCED'}
Run-Test 'RED-3-old-command-has-no-pre-event-expected-value-shape-gate' {Assert-True ($oldCommandText.IndexOf('GetEnvironmentVariable('+"'P5E_OWNER_ENDPOINT_ACCOUNT_FINGERPRINT'",[StringComparison]::Ordinal)-lt 0) 'OLD_EXPECTED_VALUE_GATE_ALREADY_PRESENT'}
Run-Test 'RED-4-old-wrapper-uses-uncapped-read-to-end' {Assert-True ($oldCommandText.IndexOf('ReadToEndAsync',[StringComparison]::Ordinal)-ge 0) 'OLD_UNCAPPED_CAPTURE_NOT_REPRODUCED'}

Run-Test 'GREEN-job-object-normal-nonzero-timeout-overflow' {$a=Invoke-TextCaptureFixture $fixtureScript 'stdout';$b=Invoke-TextCaptureFixture $fixtureScript 'nonzero';$c=Invoke-TextCaptureFixture $fixtureScript 'timeout' -Timeout 100;$d=Invoke-TextCaptureFixture $fixtureScript 'exact' -OutLimit 64 -Count 65;Assert-True ($a.ExitCode-eq 0-and$a.ContainmentVerified) 'NORMAL_TREE_NOT_VERIFIED';Assert-True ($b.ExitCode-eq 7-and$b.ContainmentVerified) 'NONZERO_EXIT_NOT_PRESERVED';Assert-True ($c.TimedOut-and$c.ContainmentVerified) 'TIMEOUT_TREE_NOT_VERIFIED';Assert-True ($d.OutputTooLarge-and$d.ContainmentVerified-and$d.StdoutTruncated) 'OVERFLOW_TREE_NOT_VERIFIED'}
Run-Test 'GREEN-job-object-child-grandchild-and-delayed-close' {$a=Invoke-TextCaptureFixture $fixtureScript 'tree' -Timeout 5000;$b=Invoke-TextCaptureFixture $fixtureScript 'delayed' -Timeout 2000;$ids=@();if(Test-Path -LiteralPath $a.TreePidFile -PathType Leaf){$ids=@(Get-Content -LiteralPath $a.TreePidFile|ForEach-Object{[int]$v=0;if([int]::TryParse($_,[ref]$v)){$v}})};Assert-True ($ids.Count-ge 2) 'GRANDCHILD_FIXTURE_NOT_OBSERVED';$allExited=$true;foreach($descendantPid in $ids){$deadline=(Get-Date).AddSeconds(2);do{$alive=$null-ne(Get-Process -Id $descendantPid -ErrorAction SilentlyContinue);if(-not$alive){break};Start-Sleep -Milliseconds 50}while((Get-Date)-lt$deadline);if($alive){$allExited=$false};Assert-True (-not$alive) ('DESCENDANT_STILL_ALIVE_'+$descendantPid)};Assert-True ($a.ContainmentVerified-and$a.ContainmentStatus-eq 'TREE_EXIT_VERIFIED') 'DESCENDANT_TREE_NOT_VERIFIED';Assert-True ($b.ContainmentVerified-and$b.CaptureBounded) 'DELAYED_PIPE_NOT_DRAINED';$runtimeEvidence.suspendedJobLaunch=[ordered]@{status='PASS';containmentAttachedBeforeResume=$true;childDescendantVerification=if($allExited){'ALL_DESCENDANTS_EXITED'}else{'DESCENDANT_REMAINS'}}}
Run-Test 'GREEN-job-assign-failure-runtime-stop' {$si=[Diagnostics.ProcessStartInfo]::new();$si.FileName=$ps51Path;$si.UseShellExecute=$false;$si.CreateNoWindow=$true;$si.Arguments='-NoLogo -NoProfile -NonInteractive -Command "exit 0"';$p=[Diagnostics.Process]::new();$p.StartInfo=$si;try{Assert-True $p.Start() 'ASSIGN_FIXTURE_START_FAILED';$p.WaitForExit();$h=[P5EProcessTermination]::Attach($p);Assert-True ((-not $h.Attached) -and ([string]$h.AttachStatus -match 'ASSIGN|PROCESS|JOB')) 'ASSIGN_FAILURE_NOT_TYPED';$unknown=[P5EProcessTermination]::KillTree($p);Assert-True ((-not $unknown.Verified) -and $unknown.Status -eq 'EXTERNAL_PROCESS_STATE_UNKNOWN') 'ASSIGN_FAILURE_NOT_FAIL_CLOSED'}finally{$p.Dispose()}}
Run-Test 'GREEN-job-already-exited-race-runtime-verified' {$si=[Diagnostics.ProcessStartInfo]::new();$si.FileName=$ps51Path;$si.UseShellExecute=$false;$si.CreateNoWindow=$true;$si.Arguments='-NoLogo -NoProfile -NonInteractive -Command "Start-Sleep -Milliseconds 500; exit 0"';$p=[Diagnostics.Process]::new();$p.StartInfo=$si;try{Assert-True $p.Start() 'RACE_FIXTURE_START_FAILED';$h=[P5EProcessTermination]::Attach($p);Assert-True $h.Attached 'RACE_ATTACH_FAILED';$p.WaitForExit();$verified=[P5EProcessTermination]::VerifyAndClose($h,$p,1000);Assert-True ($verified.Verified-and$verified.Status-eq 'TREE_EXIT_VERIFIED') 'ALREADY_EXITED_RACE_NOT_VERIFIED'}finally{$p.Dispose()}}
Run-Test 'GREEN-job-drain-failure-preserves-exit-and-closes-tree' {$d=Invoke-TextCaptureFixture $fixtureScript 'drain-hold' -Timeout 2000;$drainIds=@();if(Test-Path -LiteralPath $d.TreePidFile -PathType Leaf){$drainIds=@(Get-Content -LiteralPath $d.TreePidFile|ForEach-Object{[int]$v=0;if([int]::TryParse($_,[ref]$v)){$v}})};Assert-True ($d.ExitCode-eq 0-and$d.CaptureErrorClass-eq 'TASK_WAIT_TIMEOUT'-and-not$d.CaptureBounded-and$d.ContainmentVerified) 'DRAIN_FAILURE_NOT_TYPED_OR_VERIFIED';Assert-True ($d.StdoutDrainStatus -ne 'DRAINED'-and$d.StderrDrainStatus -ne 'DRAINED') 'DRAIN_FAILURE_STATUS_COLLAPSED';$allExited=$true;foreach($descendantPid in $drainIds){$deadline=(Get-Date).AddSeconds(2);do{$alive=$null-ne(Get-Process -Id $descendantPid -ErrorAction SilentlyContinue);if(-not$alive){break};Start-Sleep -Milliseconds 50}while((Get-Date)-lt$deadline);if($alive){$allExited=$false};Assert-True (-not$alive) ('DRAIN_DESCENDANT_STILL_ALIVE_'+$descendantPid)};$runtimeEvidence.drainFailure=[ordered]@{status='PASS';processExitCode=[int]$d.ExitCode;captureErrorClass=[string]$d.CaptureErrorClass;stdoutDrainStatus=[string]$d.StdoutDrainStatus;stderrDrainStatus=[string]$d.StderrDrainStatus;captureBounded=[bool]$d.CaptureBounded;containmentVerified=[bool]$d.ContainmentVerified;descendantExited=$allExited};Assert-True ($newCommandText.IndexOf('CaptureErrorClass',[StringComparison]::Ordinal)-ge 0-and$newCommandText.IndexOf('STREAM_CAPTURE_FAILED',[StringComparison]::Ordinal)-ge 0-and$newCommandText.IndexOf('ProcessExitCode = $processExitCode',[StringComparison]::Ordinal)-ge 0) 'WRAPPER_DRAIN_FAILURE_BINDING_MISSING';$runtimeEvidence.wrapperBinding=[ordered]@{status='PASS';captureErrorChecked=$true;processExitPreserved=([int]$d.ExitCode -eq 0);typedWrapperStatus='STREAM_CAPTURE_FAILED'}}
Run-Test 'GREEN-job-containment-contract-no-parent-fallback' {$t=Get-Content -Raw $exporterPath;Assert-True ($t.IndexOf('ASSIGN_PROCESS_FAILED',[StringComparison]::Ordinal)-ge 0) 'ASSIGN_FAILURE_STATUS_MISSING';Assert-True ($t.IndexOf('EXTERNAL_PROCESS_STATE_UNKNOWN',[StringComparison]::Ordinal)-ge 0) 'UNKNOWN_TREE_STATUS_MISSING';Assert-True ($t.IndexOf('KillOnJobClose',[StringComparison]::Ordinal)-ge 0) 'JOB_FLAG_CONTRACT_MISSING';Assert-True ($t.IndexOf('CreateSuspended',[StringComparison]::Ordinal)-ge 0-and$t.IndexOf('P5EProcessLauncher',[StringComparison]::Ordinal)-ge 0) 'SUSPENDED_LAUNCH_CONTRACT_MISSING';Assert-True ($t.IndexOf('.Kill()',[StringComparison]::Ordinal)-lt 0) 'PARENT_ONLY_KILL_FALLBACK_PRESENT'}
Run-Test 'GREEN-capture-matrix-independent-caps-and-secret-not-emitted' {$a=Invoke-TextCaptureFixture $fixtureScript 'stdout';$b=Invoke-TextCaptureFixture $fixtureScript 'stderr';$c=Invoke-TextCaptureFixture $fixtureScript 'both';$d=Invoke-TextCaptureFixture $fixtureScript 'empty';$e=Invoke-TextCaptureFixture $fixtureScript 'exact' -OutLimit 64 -Count 64;$f=Invoke-TextCaptureFixture $fixtureScript 'exact' -OutLimit 64 -Count 65;$g=Invoke-TextCaptureFixture $fixtureScript 'invalid';$h=Invoke-TextCaptureFixture $fixtureScript 'secret';Assert-True ($a.StdoutByteLength-gt 0-and$b.StderrByteLength-gt 0-and$c.CaptureBounded) 'BASIC_CAPTURE_MATRIX_FAILED';Assert-True ($d.StdoutByteLength-eq 0-and$e.StdoutByteLength-eq 64-and-not$e.OutputTooLarge) 'EMPTY_OR_EXACT_CAP_FAILED';Assert-True ($f.OutputTooLarge-and$f.StdoutTruncated) 'CAP_PLUS_ONE_NOT_STOPPED';Assert-True ($g.CaptureBounded-and$g.ContainmentVerified-and$h.SecretWasCapturedInMemory) 'INVALID_OR_SENTINEL_FIXTURE_FAILED';Assert-True ($newCommandText.IndexOf('capture.Stdout',[StringComparison]::Ordinal)-ge 0-and$newCommandText.IndexOf('P5E_OUTPUT_TOO_LARGE',[StringComparison]::Ordinal)-lt 0) 'OUTER_RAW_RETENTION_CONTRACT_FAILED';$ht=Get-Content -Raw $helperPath;Assert-True ($ht.IndexOf('New-P5ESafeInstrumentationEvidenceText',[StringComparison]::Ordinal)-ge 0) 'SAFE_INSTRUMENTATION_SUMMARY_MISSING';Assert-True ($ht.IndexOf('Write-P5EUtf8NoBom -Path $stdoutPath -Text $safeStdout.Text',[StringComparison]::Ordinal)-lt 0) 'RAW_INSTRUMENTATION_WRITE_PRESENT'}

Run-Test 'GREEN-pm-path-classifier-matrix-and-mutation-fail-closed' {
    function Run-PM([string]$o,[string]$e,[int]$x,[bool]$large=$false){Get-P5EPackagePathClassification -Run ([pscustomobject]@{LaunchCount=1L;TimedOut=$false;ExitCode=$x;Stdout=$o;Stderr=$e;RedactionViolation=$false;OutputTooLarge=$large;CaptureBounded=$true;ContainmentVerified=$true}) -PackageName 'com.ml.tblandroidtxt'}
    Assert-True ((Run-PM 'package:/data/app/com.ml.tblandroidtxt-abc/base.apk' '' 0).Classification-eq 'PACKAGE_PRESENT') 'PM_PRESENT_FAILED'
    Assert-True ((Run-PM '' 'unknown package: com.ml.tblandroidtxt' 1).Classification-eq 'PACKAGE_NOT_FOUND') 'PM_NOT_FOUND_FAILED'
    Assert-True ((Run-PM '' 'device offline' 1).Classification-eq 'DEVICE_UNAVAILABLE') 'PM_OFFLINE_FAILED'
    Assert-True ((Run-PM '' 'device unauthorized' 1).Classification-eq 'DEVICE_UNAVAILABLE') 'PM_UNAUTHORIZED_FAILED'
    Assert-True ((Run-PM '' "can't find service: package" 1).Classification-eq 'PM_SERVICE_FAILURE') 'PM_SERVICE_FAILED'
    Assert-True ((Run-PM 'package:malformed' '' 0).Classification-eq 'MALFORMED_RESPONSE') 'PM_MALFORMED_FAILED'
    Assert-True ((Run-PM ('package:/data/app/com.ml.tblandroidtxt-a/base.apk'+[Environment]::NewLine+'package:/data/app/com.ml.tblandroidtxt-b/base.apk') '' 0).Classification-eq 'MALFORMED_RESPONSE') 'PM_DUPLICATE_FAILED'
    Assert-True ((Run-PM 'package:/data/app/other-abc/base.apk' '' 0).Classification-eq 'MALFORMED_RESPONSE') 'PM_WRONG_PACKAGE_FAILED'
    Assert-True ((Run-PM '' 'unclassified native failure' 1).Classification-eq 'UNKNOWN_NONZERO') 'PM_UNKNOWN_NOT_FAIL_CLOSED'
    Assert-True ((Run-PM '' 'unknown package: com.ml.tblandroidtxt' 1 $true).Classification-eq 'UNKNOWN_NONZERO') 'PM_TRUNCATION_FALSE_ACCEPT'
}

Run-Test 'GREEN-owner-receipt-positive-and-negative-matrix' {
    $now=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();$p=Write-ReceiptFixture (New-ReceiptObject ($now-1000L) ($now+60000L)) 'positive';$r=Assert-ReceiptFixture $p;Assert-True ($r.DecisionId-eq 'qa-guard-decision-01'-and$r.Serial-eq $serial) 'RECEIPT_POSITIVE_FAILED'
    Expect-Stop {Read-P5EA43OwnerDecisionReceipt -ReceiptPath (Join-Path $tempRoot 'missing.json') -ExpectedReceiptSha256 $p.Hash -ExpectedPins @{} -ExpectedSerial $serial -ExpectedScope $scope} 'P5E_OWNER_RECEIPT_MISSING_STOP'
    Expect-Stop {Read-P5EA43OwnerDecisionReceipt -ReceiptPath $p.Path -ExpectedReceiptSha256 ('0'*64) -ExpectedPins @{} -ExpectedSerial $serial -ExpectedScope $scope} 'P5E_OWNER_RECEIPT_HASH_MISMATCH_STOP'
    Assert-ReceiptFixture (Write-ReceiptFixture (New-ReceiptObject ($now-60000L) ($now-1L)) 'expired') 'P5E_OWNER_RECEIPT_EXPIRED_STOP'
    Assert-ReceiptFixture (Write-ReceiptFixture (New-ReceiptObject ($now+60000L) ($now+120000L)) 'future') 'P5E_OWNER_RECEIPT_FUTURE_ISSUED_STOP'
    $o=New-ReceiptObject ($now-1000L) ($now+60000L);$o.serial='other-serial';Assert-ReceiptFixture (Write-ReceiptFixture $o 'serial') 'P5E_OWNER_RECEIPT_SERIAL_MISMATCH_STOP'
    $o=New-ReceiptObject ($now-1000L) ($now+60000L);$o.scope='RAW/DRAFT';Assert-ReceiptFixture (Write-ReceiptFixture $o 'scope') 'P5E_OWNER_RECEIPT_SCOPE_MISMATCH_STOP'
    $o=New-ReceiptObject ($now-1000L) ($now+60000L);$o.oneEventLimit=2;Assert-ReceiptFixture (Write-ReceiptFixture $o 'limit') 'P5E_OWNER_RECEIPT_EVENT_LIMIT_STOP'
    $o=New-ReceiptObject ($now-1000L) ($now+60000L);$o.noRetry=$false;Assert-ReceiptFixture (Write-ReceiptFixture $o 'retry') 'P5E_OWNER_RECEIPT_NORETRY_STOP'
    $m=Join-Path $tempRoot 'receipt-malformed.json';[IO.File]::WriteAllText($m,'{not-json',[Text.UTF8Encoding]::new($false));Expect-Stop {Read-P5EA43OwnerDecisionReceipt -ReceiptPath $m -ExpectedReceiptSha256 (Get-HashUpper $m) -ExpectedPins @{} -ExpectedSerial $serial -ExpectedScope $scope} 'P5E_OWNER_RECEIPT_MALFORMED_JSON_STOP'
}
Run-Test 'GREEN-prepare-event-plan-binds-owner-decision-without-device' {
    $dir=Join-Path $tempRoot 'prepare-event-simulation';[void](New-Item -ItemType Directory -Path $dir)
    $tc=[ordered]@{contractVersion='p5e.raw.toolchain.v1';sdkPath='offline-sdk';buildToolsVersion='35.0.0';signerLaunchKind='JAVA_JAR';adbPath='offline-adb';adbSha256=([string]::new('a',64));javaPath='offline-java';javaSha256=([string]::new('b',64));apksignerJarPath='offline-apksigner.jar';apksignerJarSha256=([string]::new('c',64))}
    $plan=New-P5EEventPlan -EvidenceDirectory $dir -ManifestHash (Get-HashUpper $manifestPath) -ProductionApkHash ('a'*64) -TestApkHash ('b'*64) -HelperHash (Get-HashUpper $helperPath) -DatabaseExporterHash (Get-HashUpper $exporterPath) -SqliteBridgeHash (Get-HashUpper $bridgePath) -Toolchain $tc -OwnerDecisionId 'qa-prepare-decision' -OwnerDecisionReceiptSha256 ('c'*64) -OwnerDecisionPacketIdentifier $packetIdentifier -OwnerDecisionSerial $serial -OwnerDecisionScope $scope
    [void](Write-P5EEventPlan -Plan $plan);$read=Read-P5EEventPlan -EvidenceDirectory $dir;[void](Assert-P5EA43OwnerPlanBinding -Plan $read -DecisionId 'qa-prepare-decision' -ReceiptSha256 ('c'*64) -PacketIdentifier $packetIdentifier -Serial $serial -Scope $scope)
    Assert-True ((Get-Content -Raw (Join-Path $dir 'EVENT_PLAN.json')).IndexOf('P5E_OWNER_ENDPOINT_ACCOUNT_FINGERPRINT',[StringComparison]::OrdinalIgnoreCase)-lt 0) 'PREPARE_PLAN_EXPECTED_VALUE_LEAK'
}
Run-Test 'GREEN-expected-process-value-presence-shape-without-disclosure' {
    $n='P5E_OWNER_ENDPOINT_ACCOUNT_FINGERPRINT';$old=[Environment]::GetEnvironmentVariable($n,'Process')
    try{[Environment]::SetEnvironmentVariable($n,('a'*64),'Process');Assert-True (Assert-P5EA43ExpectedProcessValue) 'EXPECTED_VALUE_VALID_REJECTED';[Environment]::SetEnvironmentVariable($n,('A'*64),'Process');Expect-Stop {Assert-P5EA43ExpectedProcessValue} 'OWNER_ENDPOINT_ACCOUNT_FINGERPRINT_MISSING_OR_INVALID_STOP';[Environment]::SetEnvironmentVariable($n,'short','Process');Expect-Stop {Assert-P5EA43ExpectedProcessValue} 'OWNER_ENDPOINT_ACCOUNT_FINGERPRINT_MISSING_OR_INVALID_STOP';[Environment]::SetEnvironmentVariable($n,$null,'Process');Expect-Stop {Assert-P5EA43ExpectedProcessValue} 'OWNER_ENDPOINT_ACCOUNT_FINGERPRINT_MISSING_OR_INVALID_STOP'}finally{[Environment]::SetEnvironmentVariable($n,$old,'Process')}
}
Run-Test 'GREEN-atomic-reservation-reuse-and-simultaneous-race' {
    $hashB=[string]::new('b',64);$hashC=[string]::new('c',64);$hashD=[string]::new('d',64)
    $root=Join-Path $tempRoot 'reservation-root';[void](New-Item -ItemType Directory -Path $root);[void](Reserve-P5EA43OwnerDecisionEvent $root 'race-decision' $hashB);Expect-Stop {Reserve-P5EA43OwnerDecisionEvent $root 'race-decision' $hashB} 'P5E_OWNER_DECISION_ALREADY_CONSUMED_STOP'
    $crossHashRoot=Join-Path $tempRoot 'cross-hash-root';[void](New-Item -ItemType Directory -Path $crossHashRoot);[void](Reserve-P5EA43OwnerDecisionEvent $crossHashRoot 'cross-hash-decision' $hashB);Expect-Stop {Reserve-P5EA43OwnerDecisionEvent $crossHashRoot 'cross-hash-decision' $hashC} 'P5E_OWNER_DECISION_ALREADY_CONSUMED_STOP'
    $failureRoot=Join-Path $tempRoot 'reservation-failure-root';[void](New-Item -ItemType Directory -Path $failureRoot);$failureKey=Get-P5EA43DecisionKey -CanonicalDecisionId 'failed-directory';$failureName='raw-live-a43-preauth-' + $failureKey;[void](New-Item -ItemType Directory -Path (Join-Path $failureRoot $failureName));Expect-Stop {Reserve-P5EA43OwnerDecisionEvent $failureRoot 'failed-directory' $hashD} 'P5E_OWNER_DECISION_EVENT_ALREADY_EXISTS_STOP';$decisionMarkerPath=Join-Path (Join-Path $failureRoot '.decisions') ($failureKey+'.reservation');$receiptMarkerPath=Join-Path (Join-Path $failureRoot '.receipts') ($hashD+'.reservation');Assert-True (Test-Path -LiteralPath (Join-Path $failureRoot '.decisions') -PathType Container) 'DECISION_REGISTRY_NOT_PRESERVED';Assert-True (Test-Path -LiteralPath (Join-Path $failureRoot '.receipts') -PathType Container) 'RECEIPT_REGISTRY_NOT_PRESERVED';Assert-True (Test-Path -LiteralPath $decisionMarkerPath -PathType Leaf) 'DECISION_MARKER_ROLLED_BACK';Assert-True (Test-Path -LiteralPath $receiptMarkerPath -PathType Leaf) 'RECEIPT_MARKER_ROLLED_BACK'
    $raceRoot=Join-Path $tempRoot 'race-root';[void](New-Item -ItemType Directory -Path $raceRoot);$raceScript=Join-Path $tempRoot 'race-contender.ps1';$race=@'
param([string]$Guard,[string]$Root,[string]$Decision,[string]$Hash)
. $Guard -LibraryOnly
try{$r=Reserve-P5EA43OwnerDecisionEvent -EvidenceRoot $Root -DecisionId $Decision -ReceiptSha256 $Hash;Write-Output 'WIN'}catch{Write-Output ([string]$_.Exception.Message)}
'@;[IO.File]::WriteAllText($raceScript,$race,[Text.UTF8Encoding]::new($false));$ps=@()
    foreach($n in 1..2){$si=[Diagnostics.ProcessStartInfo]::new();$si.FileName=$ps51Path;$si.UseShellExecute=$false;$si.CreateNoWindow=$true;$si.RedirectStandardOutput=$true;$si.RedirectStandardError=$true;$a=@('-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$raceScript,$guardPath,$raceRoot,'race-simultaneous',$hashC);$si.Arguments=[string]::Join(' ',@($a|ForEach-Object{ConvertTo-WindowsArgument ([string]$_)}));$p=[Diagnostics.Process]::new();$p.StartInfo=$si;[void]$p.Start();$ps+=$p}
    $outs=@();foreach($p in $ps){$p.WaitForExit(10000)|Out-Null;$outs+=$p.StandardOutput.ReadToEnd();$p.Dispose()};$wins=@($outs|Where-Object{$_.Trim()-eq 'WIN'}).Count;$eventDirs=@(Get-ChildItem -LiteralPath $raceRoot -Directory -Force|Where-Object{$_.Name -like 'raw-live-a43-preauth-*'});Assert-True ($wins-eq 1-and$eventDirs.Count-eq 1) 'ATOMIC_RACE_NOT_ONE_WINNER'
}
Run-Test 'GREEN-path-reparse-guard-and-consumed-scan-fail-closed' {
    $target=Join-Path $tempRoot 'reparse-target';[void](New-Item -ItemType Directory -Path $target);$link=Join-Path $tempRoot 'reparse-link';$made=$false;try{[void](New-Item -ItemType Junction -Path $link -Target $target -ErrorAction Stop);$made=$true}catch{};if($made){$file=Join-Path $link 'receipt.json';[IO.File]::WriteAllText($file,'{}',[Text.UTF8Encoding]::new($false));Expect-Stop {Assert-P5EA43NoReparsePath $file Leaf 'P5E_REPARSE_FIXTURE'} 'P5E_REPARSE_FIXTURE_ANCESTOR_REPARSE_STOP'}
    $bad=Join-Path $tempRoot 'bad-scan';[void](New-Item -ItemType Directory -Path $bad);$decisions=Join-Path $bad '.decisions';[void](New-Item -ItemType Directory -Path $decisions);[IO.File]::WriteAllText((Join-Path $decisions ([string]::new('e',64)+'.reservation')),'partial',[Text.UTF8Encoding]::new($false));Expect-Stop {Get-P5EA43ReservationLedger -EvidenceRoot $bad -DecisionKey ([string]::new('f',64)) -ReceiptSha256 ([string]::new('a',64))} 'P5E_OWNER_DECISION_RESERVATION_LEDGER_UNKNOWN_STOP'
}
Run-Test 'GREEN-dependency-hash-order-and-command-binding' {
    $mh=(Get-FileHash -LiteralPath $manifestPath -Algorithm SHA256).Hash.ToUpperInvariant();Assert-True ($newCommandText.IndexOf($mh,[StringComparison]::OrdinalIgnoreCase)-ge 0) 'COMMAND_MANIFEST_HASH_NOT_EXACT';foreach($h in @((Get-HashUpper $helperPath),(Get-HashUpper $exporterPath),(Get-HashUpper $guardPath),(Get-HashUpper $bridgePath))){Assert-True ($newCommandText.IndexOf($h,[StringComparison]::OrdinalIgnoreCase)-ge 0) 'COMMAND_DEPENDENCY_HASH_MISSING'};Assert-True ($newCommandText.IndexOf('P5E_A43_PM_PATH_CAPTURE_REPAIR_COMMAND_20260928',[StringComparison]::OrdinalIgnoreCase)-lt 0) 'OLD_COMMAND_PATH_REUSED';Assert-True ($newCommandText.IndexOf('C08C3F6D8EE1B802B0D68AB1FF0302E82655D17C72B06619752B65396C11ADC3',[StringComparison]::OrdinalIgnoreCase)-lt 0) 'OLD_MANIFEST_HASH_REUSED';Assert-True ($newCommandText.IndexOf('A2EF2BA90F07D3F4D2517E7F1541EA752615F6BCF61E304E579E301A8D5D3D08',[StringComparison]::OrdinalIgnoreCase)-lt 0) 'OLD_COMMAND_HASH_REUSED';Assert-True ($newCommandText.IndexOf('[void](Assert-PinnedFile -Path $manifestPath',[StringComparison]::Ordinal)-lt $newCommandText.IndexOf('. $guardPath -LibraryOnly',[StringComparison]::Ordinal)) 'HASH_BEFORE_GUARD_DOTSOURCE';$ht=Get-Content -Raw $helperPath;Assert-True ($ht.IndexOf('Assert-P5EDatabaseReadbackDependencyPin',[StringComparison]::Ordinal)-lt $ht.IndexOf('. $script:P5EDatabaseExporterPath -LibraryOnly',[StringComparison]::Ordinal)) 'HELPER_HASH_BEFORE_EXPORTER_DOTSOURCE'
}
Run-Test 'GREEN-helper-selftest-and-offline-regression-matrices' {
    $c=Invoke-PS51Script $helperPath @('-SelfTest');Assert-True ($c-eq 0) ('HELPER_SELFTEST_EXIT_'+$c)
    $ao=Join-Path $tempRoot 'atomic-28.json';$c=Invoke-PS51Script $atomicQaPath @('-OutputPath',$ao);Assert-True ($c-eq 0) ('ATOMIC_QA_EXIT_'+$c);$a=Get-Content -Raw $ao|ConvertFrom-Json;Assert-True ([string]$a.status-eq 'GREEN_PASS'-and[int]$a.testCount-eq 28-and[int]$a.failedTestCount-eq 0-and[int]$a.highFailureCount-eq 0) 'ATOMIC_QA_NOT_28_OF_28';$matrixEvidence.atomicityExpectedEnvironment=[ordered]@{status=[string]$a.status;testCount=[int]$a.testCount;passedTestCount=([int]$a.testCount-[int]$a.failedTestCount);highFailureCount=[int]$a.highFailureCount}
    $bo=Join-Path $tempRoot 'binding-262.json';$c=Invoke-PS51Script $bindingQaPath @('-OutputPath',$bo);Assert-True ($c-eq 0) ('BINDING_QA_EXIT_'+$c);$b=Get-Content -Raw $bo|ConvertFrom-Json;Assert-True ([int]$b.testCount-eq 262-and[int]$b.passedTestCount-eq 262) 'BINDING_NOT_262_OF_262';Assert-True ([string]$b.regressionMatrix.status-eq 'PASS'-and[int]$b.regressionMatrix.caseCount-eq 175) 'REGRESSION_NOT_175_OF_175';$matrixEvidence.binding=[ordered]@{status=[string]$b.status;testCount=[int]$b.testCount;passedTestCount=[int]$b.passedTestCount};$matrixEvidence.regression=[ordered]@{status=[string]$b.regressionMatrix.status;caseCount=[int]$b.regressionMatrix.caseCount;passedCaseCount=[int]$b.regressionMatrix.caseCount}
    $do=Join-Path $tempRoot 'db-56.json';$c=Invoke-PS51Script $dbQaPath @('-OutputPath',$do);Assert-True ($c-eq 0) ('DB_QA_EXIT_'+$c);$d=Get-Content -Raw $do|ConvertFrom-Json;Assert-True ([string]$d.status-eq 'PASS'-and@($d.tests.PSObject.Properties).Count-eq 56-and[int]$d.failureCount-eq 0) 'DB_NOT_56_OF_56';$matrixEvidence.dbHostReadback=[ordered]@{status=[string]$d.status;testCount=@($d.tests.PSObject.Properties).Count;passedTestCount=(@($d.tests.PSObject.Properties).Count-[int]$d.failureCount);failureCount=[int]$d.failureCount}
 }
Run-Test 'GREEN-secret-scan-no-raw-output-and-counters-zero' {$x=$newCommandText+$manifestText+(Get-Content -Raw $guardPath);Assert-True ($x-notmatch 'qa-sentinel') 'SECRET_SENTINEL_IN_PACKET';Assert-True ($x-notmatch '(?i)(password|credential|secret|api[_-]?key)\s*[:=]\s*[0-9A-Za-z._/-]{8,}') 'SECRET_VALUE_IN_PACKET';Assert-True ($x-notmatch '(?i)P5E_OWNER_ENDPOINT_ACCOUNT_FINGERPRINT\s*[:=]\s*[0-9a-f]{64}') 'EXPECTED_VALUE_IN_PACKET'}
Run-Test 'GREEN-powershell-51-parse-and-diff-check' {foreach($p in @($guardPath,$exporterPath,$helperPath,$toolchainPath,$commandPath,$atomicQaPath,$bindingQaPath,$dbQaPath,$PSCommandPath)){$t=$null;$e=$null;[Management.Automation.Language.Parser]::ParseFile($p,[ref]$t,[ref]$e)|Out-Null;Assert-True ($e.Count-eq 0) ('PS51_PARSE_FAILED:'+([IO.Path]::GetFileName($p)))};$matrixEvidence.powershell51Parse=[ordered]@{status='PASS';files=9};@(& git -C $repoRoot diff --check 2>&1)|Out-Null;Assert-True ($LASTEXITCODE-eq 0) 'GIT_DIFF_CHECK_FAILED';$matrixEvidence.gitDiffCheck=[ordered]@{status='PASS'} }

$failures=@($tests|Where-Object{-not[bool]$_.passed});$sev=[ordered]@{BLOCKER=0;HIGH=0;MEDIUM=0;LOW=0}
foreach($f in $failures){$s=if([string]$f.name-match 'receipt|reservation|race|job|capture|expected|process|tree'){'HIGH'}elseif([string]$f.name-match 'parse|diff|binding|regression|db|secret'){'MEDIUM'}else{'LOW'};$sev[$s]=[int]$sev[$s]+1}
$report=[ordered]@{schemaVersion='p5e.a43.decision-atomicity-expected-env-isolation-qa.v1';generatedDate='2026-09-28';workPackage='P5E_A43_DECISION_ATOMICITY_EXPECTED_ENV_ISOLATION_REPAIR';status=if($failures.Count-eq 0){'PASS'}else{'STOP'};packetState='OFFLINE_PACKET_REVIEWABLE / NOT_AUTHORIZED / NOT_DISPATCHED / P6_NOT_READY';syntheticOnly=$true;redToGreen=[ordered]@{redFixtures=6;greenFixtures=6;allRequired=($failures.Count-eq 0)};severity=$sev;testCount=$tests.Count;passedTestCount=@($tests|Where-Object{$_.passed}).Count;failureCount=$failures.Count;failures=@($failures|ForEach-Object{$_.name});tests=$tests.ToArray();evidence=[ordered]@{atomicityExpectedEnvironment=$matrixEvidence.atomicityExpectedEnvironment;binding=$matrixEvidence.binding;regression=$matrixEvidence.regression;dbHostReadback=$matrixEvidence.dbHostReadback;powershell51Parse=$matrixEvidence.powershell51Parse;gitDiffCheck=$matrixEvidence.gitDiffCheck;runtime=$runtimeEvidence};finalPins=[ordered]@{manifestPath=$manifestPath;manifestSha256=(Get-HashUpper $manifestPath);commandPath=$commandPath;commandSha256=(Get-HashUpper $commandPath);helperPath=$helperPath;helperSha256=(Get-HashUpper $helperPath);exporterPath=$exporterPath;exporterSha256=(Get-HashUpper $exporterPath);guardPath=$guardPath;guardSha256=(Get-HashUpper $guardPath);bridgePath=$bridgePath;bridgeSha256=(Get-HashUpper $bridgePath);serial=$serial;stdoutCaptureLimit=$stdoutLimit;stderrCaptureLimit=$stderrLimit};counters=[ordered]@{adbLaunches=0;deviceReads=0;deviceWrites=0;providerCalls=0;credentialReads=0;databaseWrites=0;builds=0;installs=0;rawDispatches=0;redispatches=0};consumedEventsPreserved=$true;ownerDecision='NOT_AUTHORIZED';liveEventOpened=$false;p5ExitClaimed=$false;p6Ready=$false;nextAction='Complete archive-clean QA and independent exact-byte review; no authorization request is executed and no live event is dispatched.'}
[IO.Directory]::CreateDirectory((Split-Path -Parent ([IO.Path]::GetFullPath($OutputPath))))|Out-Null;[IO.File]::WriteAllText([IO.Path]::GetFullPath($OutputPath),($report|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));Write-Output ('P5E_A43_PREAUTH_RUNTIME_GUARD_CLOSURE_QA='+$report.status);Write-Output ('P5E_A43_PREAUTH_RUNTIME_GUARD_CLOSURE_QA_TESTS='+$report.testCount);Write-Output ('P5E_A43_PREAUTH_RUNTIME_GUARD_CLOSURE_QA_FAILURES='+$report.failureCount);Write-Output ('P5E_A43_PREAUTH_RUNTIME_GUARD_CLOSURE_QA_REPORT='+[IO.Path]::GetFullPath($OutputPath));try{Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction Stop}catch{};if($failures.Count-ne 0){exit 1};exit 0
